"use strict";

const GRAMMAR_CASES = {
  intro: "En allemand, l'article change selon le rôle du mot dans la phrase. Pour débuter, les 3 cas essentiels sont : nominatif, accusatif et datif.",
  genitiveNote: "Le génitif existe, mais tu peux le laisser pour plus tard.",
  accusativeNote: "À l'accusatif, seul le masculin change : der devient den.",
  mixedRule: "Prépositions mixtes : datif = position. Accusatif = mouvement.",
  definedArticles: [
    ["Nominatif", "der", "die", "das", "die"],
    ["Accusatif", "den", "die", "das", "die"],
    ["Datif", "dem", "der", "dem", "den (+n)"],
  ],
  indefiniteArticles: [
    ["Nominatif", "ein", "eine", "ein"],
    ["Accusatif", "einen", "eine", "ein"],
    ["Datif", "einem", "einer", "einem"],
  ],
  caseCards: [
    { title: "Nominatif = sujet", example: "Der Hund schläft.", fr: "Le chien dort." },
    { title: "Accusatif = COD", example: "Ich sehe den Hund.", fr: "Je vois le chien." },
    { title: "Datif = COI / à qui ?", example: "Ich helfe dem Mann.", fr: "J'aide l'homme." },
  ],
  prepositions: [
    { title: "Toujours datif", items: ["aus", "bei", "mit", "nach", "seit", "von", "zu"] },
    { title: "Toujours accusatif", items: ["durch", "für", "gegen", "ohne", "um"] },
    { title: "Prépositions mixtes", items: ["in", "an", "auf", "über", "unter", "vor", "hinter", "neben", "zwischen"] },
  ],
  mixedExamples: [
    { de: "Ich bin in der Stadt.", fr: "Je suis en ville." },
    { de: "Ich gehe in die Stadt.", fr: "Je vais en ville." },
  ],
  dativeVerbs: ["helfen", "danken", "gefallen", "gehören", "antworten", "folgen", "gratulieren", "schmecken", "passen", "gelingen", "fehlen", "vertrauen", "glauben", "widersprechen", "zuhören"],
  dativeVerbExample: { de: "Kannst du mir helfen?", fr: "Peux-tu m'aider ?" },
  pronouns: [
    ["ich", "mich", "mir"],
    ["du", "dich", "dir"],
    ["er", "ihn", "ihm"],
    ["sie", "sie", "ihr"],
    ["es", "es", "ihm"],
    ["wir", "uns", "uns"],
    ["ihr", "euch", "euch"],
    ["sie", "sie", "ihnen"],
    ["Sie", "Sie", "Ihnen"],
  ],
};

const TENSE_GUIDE = {
  praesens: {
    title: "Präsens",
    description: "Le présent. Il sert aussi souvent pour le futur proche : Ich komme morgen."
  },
  perfekt: {
    title: "Perfekt",
    description: "Le passé le plus courant à l'oral. La plupart des verbes utilisent haben, mais les verbes de déplacement/changement d'état utilisent souvent sein."
  },
  praeteritum: {
    title: "Präteritum",
    description: "Passé surtout utilisé à l'écrit et dans les récits. Très important pour sein, haben et les verbes modaux."
  }
};

const IRREGULAR_VERBS = [
  { inf: "sein", fr: "être", praesens: ["bin","bist","ist","sind","seid","sind"], perfekt: "ist gewesen", praeteritum: "war", note: "Le verbe le plus important. Präteritum « war » très courant à l'oral." },
  { inf: "haben", fr: "avoir", praesens: ["habe","hast","hat","haben","habt","haben"], perfekt: "hat gehabt", praeteritum: "hatte", note: "Präteritum « hatte » très courant à l'oral." },
  { inf: "werden", fr: "devenir", praesens: ["werde","wirst","wird","werden","werdet","werden"], perfekt: "ist geworden", praeteritum: "wurde" },
  { inf: "können", fr: "pouvoir", praesens: ["kann","kannst","kann","können","könnt","können"], perfekt: "hat gekonnt", praeteritum: "konnte", note: "Modal : ich/er identiques, sans terminaison." },
  { inf: "müssen", fr: "devoir", praesens: ["muss","musst","muss","müssen","müsst","müssen"], perfekt: "hat gemusst", praeteritum: "musste" },
  { inf: "wollen", fr: "vouloir", praesens: ["will","willst","will","wollen","wollt","wollen"], perfekt: "hat gewollt", praeteritum: "wollte" },
  { inf: "sollen", fr: "devoir / être censé", praesens: ["soll","sollst","soll","sollen","sollt","sollen"], perfekt: "hat gesollt", praeteritum: "sollte" },
  { inf: "dürfen", fr: "avoir le droit", praesens: ["darf","darfst","darf","dürfen","dürft","dürfen"], perfekt: "hat gedurft", praeteritum: "durfte" },
  { inf: "mögen", fr: "aimer bien", praesens: ["mag","magst","mag","mögen","mögt","mögen"], perfekt: "hat gemocht", praeteritum: "mochte" },
  { inf: "wissen", fr: "savoir", praesens: ["weiß","weißt","weiß","wissen","wisst","wissen"], perfekt: "hat gewusst", praeteritum: "wusste" },
  { inf: "gehen", fr: "aller", praesens: null, perfekt: "ist gegangen", praeteritum: "ging" },
  { inf: "kommen", fr: "venir", praesens: null, perfekt: "ist gekommen", praeteritum: "kam" },
  { inf: "sehen", fr: "voir", praesens: ["sehe","siehst","sieht","sehen","seht","sehen"], perfekt: "hat gesehen", praeteritum: "sah" },
  { inf: "essen", fr: "manger", praesens: ["esse","isst","isst","essen","esst","essen"], perfekt: "hat gegessen", praeteritum: "aß" },
  { inf: "trinken", fr: "boire", praesens: null, perfekt: "hat getrunken", praeteritum: "trank" },
  { inf: "geben", fr: "donner", praesens: ["gebe","gibst","gibt","geben","gebt","geben"], perfekt: "hat gegeben", praeteritum: "gab" },
  { inf: "nehmen", fr: "prendre", praesens: ["nehme","nimmst","nimmt","nehmen","nehmt","nehmen"], perfekt: "hat genommen", praeteritum: "nahm" },
  { inf: "sprechen", fr: "parler", praesens: ["spreche","sprichst","spricht","sprechen","sprecht","sprechen"], perfekt: "hat gesprochen", praeteritum: "sprach" },
  { inf: "lesen", fr: "lire", praesens: ["lese","liest","liest","lesen","lest","lesen"], perfekt: "hat gelesen", praeteritum: "las" },
  { inf: "fahren", fr: "conduire / aller en véhicule", praesens: ["fahre","fährst","fährt","fahren","fahrt","fahren"], perfekt: "ist gefahren", praeteritum: "fuhr" },
  { inf: "laufen", fr: "courir / marcher", praesens: ["laufe","läufst","läuft","laufen","lauft","laufen"], perfekt: "ist gelaufen", praeteritum: "lief" },
  { inf: "schlafen", fr: "dormir", praesens: ["schlafe","schläfst","schläft","schlafen","schlaft","schlafen"], perfekt: "hat geschlafen", praeteritum: "schlief" },
  { inf: "helfen", fr: "aider (+ datif)", praesens: ["helfe","hilfst","hilft","helfen","helft","helfen"], perfekt: "hat geholfen", praeteritum: "half", note: "Toujours suivi du datif : Kannst du mir helfen ?" },
  { inf: "finden", fr: "trouver", praesens: null, perfekt: "hat gefunden", praeteritum: "fand", note: "Präsens régulier : du findest, er findet." },
  { inf: "bleiben", fr: "rester", praesens: null, perfekt: "ist geblieben", praeteritum: "blieb" },
  { inf: "stehen", fr: "être debout", praesens: null, perfekt: "hat gestanden", praeteritum: "stand" },
  { inf: "verstehen", fr: "comprendre", praesens: null, perfekt: "hat verstanden", praeteritum: "verstand", note: "ver + stehen : se conjugue comme stehen, sans ge- au Perfekt." },
  { inf: "tun", fr: "faire", praesens: ["tue","tust","tut","tun","tut","tun"], perfekt: "hat getan", praeteritum: "tat" },
  { inf: "heißen", fr: "s'appeler", praesens: ["heiße","heißt","heißt","heißen","heißt","heißen"], perfekt: "hat geheißen", praeteritum: "hieß" },
  { inf: "schreiben", fr: "écrire", praesens: null, perfekt: "hat geschrieben", praeteritum: "schrieb" }
];


const gp = (id, title, explanation, examples, pitfall = "", extra = {}) => ({
  id,
  title,
  explanation,
  examples: examples.map(([de, fr]) => ({ de, fr })),
  ...(pitfall ? { pitfall } : {}),
  ...extra,
});
const tbl = (headers, rows) => ({ headers, rows });
const CASE_LINK = { caseLink: true };

const GRAMMAR_LEVELS_CONTENT = [
  {
    level: "A1",
    points: [
      gp("word-order-main", "Ordre des mots : verbe en 2e position", "Dans une phrase déclarative simple, le verbe conjugué est toujours en deuxième position. Le premier élément peut être le sujet, un complément de temps ou un lieu ; si tu mets un complément en premier, le sujet passe après le verbe.", [["Ich lerne Deutsch.", "J'apprends l'allemand."], ["Heute lerne ich Deutsch.", "Aujourd'hui, j'apprends l'allemand."], ["In Berlin wohnt meine Schwester.", "Ma soeur habite à Berlin."]], "Ne garde pas automatiquement l'ordre français sujet + verbe. Après Heute, on dit Heute lerne ich, pas Heute ich lerne."),
      gp("yes-no-questions", "Questions oui/non : verbe en 1re position", "Pour une question à laquelle on répond par oui ou non, le verbe conjugué passe en première position. On n'ajoute pas est-ce que : la position du verbe suffit.", [["Kommst du aus Frankreich?", "Viens-tu de France ?"], ["Hast du Zeit?", "As-tu le temps ?"], ["Möchten Sie Kaffee?", "Voulez-vous du café ?"]], "Ne traduis pas est-ce que par un mot allemand. C'est la structure verbale qui marque la question."),
      gp("w-fragen", "Les W-Fragen", "Les questions ouvertes commencent souvent par un mot en w. Le mot interrogatif vient en premier, puis le verbe conjugué, puis le sujet.", [["Wo wohnst du?", "Où habites-tu ?"], ["Wann kommst du?", "Quand viens-tu ?"], ["Wohin gehst du?", "Où vas-tu ?"]], "wenn ne sert pas à demander quand. Pour une question, utilise wann.", { table: tbl(["Mot", "Sens"], [["wer", "qui"], ["was", "quoi"], ["wo", "où, position"], ["wann", "quand"], ["wie", "comment"], ["warum", "pourquoi"], ["woher", "d'où"], ["wohin", "vers où"]]) }),
      gp("present-tense", "Le présent des verbes réguliers", "Le présent sert pour maintenant, les habitudes et souvent le futur proche quand un marqueur de temps est clair. Les verbes réguliers prennent les terminaisons -e, -st, -t, -en, -t, -en.", [["Ich mache eine Pause.", "Je fais une pause."], ["Wir lernen jeden Abend.", "Nous étudions chaque soir."], ["Morgen besuche ich meine Freundin.", "Demain, je rends visite à mon amie."]], "Le présent allemand peut parler du futur si le contexte est clair : Morgen komme ich.", { table: tbl(["Sujet", "machen"], [["ich", "mache"], ["du", "machst"], ["er/sie/es", "macht"], ["wir", "machen"], ["ihr", "macht"], ["sie/Sie", "machen"]]) }),
      gp("sein-haben-present", "sein et haben au présent", "sein et haben sont irréguliers et indispensables. Apprends-les comme des blocs : ils servent seuls, mais aussi dans beaucoup de temps composés plus tard.", [["Ich bin müde.", "Je suis fatigué."], ["Sie hat ein Auto.", "Elle a une voiture."], ["Wir sind zu Hause.", "Nous sommes à la maison."]], "Ne cherche pas une logique régulière : ich bin et du bist doivent être mémorisés tels quels.", { table: tbl(["Sujet", "sein", "haben"], [["ich", "bin", "habe"], ["du", "bist", "hast"], ["er/sie/es", "ist", "hat"], ["wir", "sind", "haben"], ["ihr", "seid", "habt"], ["sie/Sie", "sind", "haben"]]) }),
      gp("personal-pronouns-nominative", "Pronoms personnels au nominatif", "Le nominatif sert surtout pour le sujet. Ces pronoms répondent à la question qui fait l'action ? Les autres cas changent les formes ; ici on reste au sujet.", [["Ich wohne in Lyon.", "J'habite à Lyon."], ["Sie kommt aus Wien.", "Elle vient de Vienne."], ["Sie sprechen Deutsch.", "Vous parlez allemand."]], "sie peut vouloir dire elle, ils ou elles. La majuscule Sie marque le vous de politesse.", { ...CASE_LINK, table: tbl(["Allemand", "Français"], [["ich", "je"], ["du", "tu"], ["er", "il"], ["sie", "elle"], ["es", "il/elle neutre"], ["wir", "nous"], ["ihr", "vous familier pluriel"], ["sie", "ils/elles"], ["Sie", "vous de politesse"]]) }),
      gp("indefinite-articles-kein", "ein/eine et la négation kein", "ein/eine correspond souvent à un/une. Pour dire pas de devant un nom, l'allemand utilise kein, qui se comporte comme un article et prend des terminaisons.", [["Das ist ein Stuhl.", "C'est une chaise."], ["Ich habe keine Tasche.", "Je n'ai pas de sac."], ["Er hat kein Auto.", "Il n'a pas de voiture."]], "kein ne nie pas un verbe : pour je ne viens pas, dis Ich komme nicht, pas Ich komme kein.", { ...CASE_LINK, table: tbl(["Forme", "Exemple"], [["ein", "ein Tisch"], ["eine", "eine Lampe"], ["kein", "kein Tisch"], ["keine", "keine Lampe"]]) }),
      gp("nicht-kein", "Négation : nicht vs kein", "kein nie un nom avec article indéfini ou sans article. nicht nie un verbe, un adjectif, une information précise ou toute une phrase.", [["Ich habe kein Auto.", "Je n'ai pas de voiture."], ["Ich komme heute nicht.", "Je ne viens pas aujourd'hui."], ["Das ist nicht teuer.", "Ce n'est pas cher."]], "Le français utilise ne... pas partout ; l'allemand choisit entre kein et nicht selon ce qui est nié.", { ...CASE_LINK, table: tbl(["Utilise", "Pour nier"], [["kein", "un nom : pas de, aucun"], ["nicht", "un verbe, un adjectif, une information précise"]]) }),
      gp("noun-plurals-patterns", "Pluriels des noms : grands modèles", "Il n'y a pas une seule règle fiable pour le pluriel. À A1, repère les grands modèles et apprends le pluriel avec le nom : -e, -en, -er, umlaut + -e, -s.", [["Ich habe zwei Bücher.", "J'ai deux livres."], ["Hier sind viele Frauen.", "Il y a beaucoup de femmes ici."], ["Die Autos sind teuer.", "Les voitures sont chères."]], "Ne déduis pas toujours le pluriel depuis le français. Note le pluriel dès que tu apprends un nom.", { table: tbl(["Modèle", "Exemple"], [["-e", "der Tisch, die Tische"], ["-en", "die Frau, die Frauen"], ["-er", "das Kind, die Kinder"], ["ä + -e", "der Stuhl, die Stühle"], ["-s", "das Auto, die Autos"]]) }),
      gp("modal-verbs-present", "Verbes modaux au présent", "Les modaux expriment une possibilité, une obligation, une permission ou un souhait. Le modal est conjugué en deuxième position ; l'autre verbe reste à l'infinitif en fin de phrase.", [["Ich kann Deutsch sprechen.", "Je peux parler allemand."], ["Du musst heute arbeiten.", "Tu dois travailler aujourd'hui."], ["Darf ich hier sitzen?", "Ai-je le droit de m'asseoir ici ?"]], "Ne conjugue pas le verbe final : ich kann kommen, pas ich kann komme.", { table: tbl(["Modal", "Idée"], [["können", "pouvoir, savoir faire"], ["müssen", "devoir, être obligé"], ["wollen", "vouloir"], ["sollen", "devoir selon une consigne"], ["dürfen", "avoir le droit"]]) }),
      gp("moechten-polite", "möchten pour exprimer un souhait poli", "möchten signifie je voudrais, tu voudrais... Il est plus poli que wollen dans un café, un magasin ou une demande. wollen reste plus direct et peut sonner brusque.", [["Ich möchte einen Kaffee.", "Je voudrais un café."], ["Wir möchten bezahlen.", "Nous voudrions payer."], ["Möchten Sie Wasser?", "Voulez-vous de l'eau ?"]], "Je veux se traduit souvent par ich möchte en contexte poli, pas par ich will.", { table: tbl(["Sujet", "möchten"], [["ich", "möchte"], ["du", "möchtest"], ["er/sie/es", "möchte"], ["wir", "möchten"], ["ihr", "möchtet"], ["sie/Sie", "möchten"]]) }),
      gp("separable-verbs-present", "Verbes à particule séparable au présent", "Certains verbes ont une particule qui se détache dans la phrase principale. Le verbe conjugué reste en deuxième position et la particule va à la fin.", [["Ich stehe um sieben Uhr auf.", "Je me lève à sept heures."], ["Wir kaufen heute ein.", "Nous faisons les courses aujourd'hui."], ["Rufst du mich an?", "Tu m'appelles ?"]], "N'oublie pas la particule finale : ich stehe auf, pas seulement ich stehe."),
      gp("imperative", "L'impératif", "L'impératif sert à donner une consigne, une invitation ou une instruction. Les formes principales sont du, ihr et Sie ; avec Sie, le pronom reste visible.", [["Komm bitte!", "Viens s'il te plaît !"], ["Wartet hier!", "Attendez ici !"], ["öffnen Sie das Fenster!", "Ouvrez la fenêtre !"]], "Avec Sie, garde Sie après le verbe : Kommen Sie, öffnen Sie.", { table: tbl(["Forme", "Exemple"], [["du", "Komm!"], ["ihr", "Kommt!"], ["Sie", "Kommen Sie!"]]) }),
      gp("possessives", "Les possessifs", "Les possessifs indiquent à qui appartient quelque chose : mein, dein, sein, ihr, unser, euer, Ihr. Ils se placent devant le nom et changent selon le genre, le nombre et le cas.", [["Das ist mein Bruder.", "C'est mon frère."], ["Wo ist deine Tasche?", "Où est ton sac ?"], ["Unsere Wohnung ist klein.", "Notre appartement est petit."]], "sein et ihr dépendent du possesseur : sein Vater = son père à lui ; ihr Vater = son père à elle ou leur père.", { ...CASE_LINK, table: tbl(["Possessif", "Sens"], [["mein", "mon, ma, mes"], ["dein", "ton, ta, tes"], ["sein", "son, sa, ses à lui"], ["ihr", "son, sa, ses à elle / leur(s)"], ["unser", "notre, nos"], ["euer", "votre, vos"], ["Ihr", "votre, vos, politesse"]]) }),
      gp("es-gibt", "es gibt + accusatif", "es gibt signifie il y a. Le groupe nominal qui suit est à l'accusatif, même si en français on ne voit pas de changement.", [["Es gibt einen Supermarkt.", "Il y a un supermarché."], ["Es gibt hier keine Bank.", "Il n'y a pas de banque ici."], ["Gibt es ein Problem?", "Y a-t-il un problème ?"]], "Après es gibt, le masculin devient einen : Es gibt einen Park.", CASE_LINK),
      gp("time-prepositions-am-um-im", "Prépositions de temps : am, um, im", "am sert souvent pour les jours et moments de journée, um pour l'heure précise, im pour les mois et saisons. Ces formes sont à apprendre comme expressions de temps.", [["Der Kurs beginnt am Montag.", "Le cours commence lundi."], ["Wir treffen uns um acht Uhr.", "Nous nous retrouvons à huit heures."], ["Im Januar ist es kalt.", "En janvier, il fait froid."]], "Ne traduis pas en/à/le mécaniquement : am Montag, um acht Uhr, im Januar.", { table: tbl(["Préposition", "Usage", "Exemple"], [["am", "jour, date, moment", "am Montag"], ["um", "heure précise", "um 8 Uhr"], ["im", "mois, saison", "im Januar"]]) }),
      gp("numbers-time-date", "Nombres, heure et date : règles clés", "À A1, il faut savoir comprendre les nombres, donner l'heure simple et dire une date. Pour l'heure officielle, on lit souvent heure + Uhr + minutes.", [["Es ist neun Uhr dreißig.", "Il est neuf heures trente."], ["Heute ist der dritte April.", "Aujourd'hui, nous sommes le 3 avril."], ["Ich komme am Freitag.", "Je viens vendredi."]], "Les dates prennent souvent une terminaison : der dritte April, am dritten April."),
      gp("gern-lieber", "gern, lieber, am liebsten", "gern exprime ce qu'on aime faire. lieber compare deux préférences. am liebsten indique la préférence la plus forte.", [["Ich trinke gern Tee.", "J'aime boire du thé."], ["Ich trinke lieber Kaffee.", "Je préfère boire du café."], ["Am liebsten trinke ich Wasser.", "Ce que je préfère boire, c'est l'eau."]], "gern porte sur l'action, pas sur un objet seul : ich trinke gern Tee."),
      gp("ja-nein-doch", "ja, nein, doch", "ja confirme une phrase positive, nein refuse ou nie, doch contredit une question ou phrase négative. doch est essentiel car le français n'a pas un équivalent unique.", [["Kommst du? Ja, ich komme.", "Tu viens ? Oui, je viens."], ["Kommst du nicht? Doch, ich komme.", "Tu ne viens pas ? Si, je viens."], ["Hast du kein Auto? Nein, ich habe kein Auto.", "Tu n'as pas de voiture ? Non, je n'ai pas de voiture."]], "Pour répondre si à une question négative, utilise doch, pas ja.", { table: tbl(["Réponse", "Quand l'utiliser"], [["ja", "confirmer une question positive"], ["nein", "refuser ou confirmer une négation"], ["doch", "contredire une négation"]]) }),
      gp("coordinating-conjunctions", "aber, und, oder, denn : ordre normal", "Ces conjonctions relient deux éléments ou deux phrases. Après und, oder, aber et denn, l'ordre reste normal : le connecteur ne pousse pas le verbe à la fin.", [["Ich lerne Deutsch, aber ich spreche noch langsam.", "J'apprends l'allemand, mais je parle encore lentement."], ["Ich bleibe zu Hause, denn ich bin krank.", "Je reste à la maison car je suis malade."], ["Du kannst Tee trinken oder du nimmst Kaffee.", "Tu peux boire du thé ou tu prends du café."]], "denn ne fonctionne pas comme weil : après denn, le verbe ne va pas à la fin.", { table: tbl(["Conjonction", "Sens"], [["und", "et"], ["oder", "ou"], ["aber", "mais"], ["denn", "car"]]) })
    ]
  },

  {
    level: "A2",
    points: [
      gp("perfekt", "Le Perfekt", "Le Perfekt est le passé le plus courant à l'oral. Il se forme avec haben ou sein au présent + participe passé en fin de phrase. On ne l'utilise pas pour tout dans un style écrit soutenu, mais il est central au niveau A2.", [["Ich habe Deutsch gelernt.", "J'ai appris l'allemand."], ["Wir sind nach Hamburg gefahren.", "Nous sommes allés à Hambourg."], ["Ich habe mein Zimmer aufgeräumt.", "J'ai rangé ma chambre."]], "sein s'emploie surtout avec un changement de lieu ou d'état : gehen, fahren, kommen, aufstehen.", { table: tbl(["Type", "Forme fréquente"], [["Régulier", "ge- + radical + -t"], ["Irrégulier", "souvent ge- + radical + -en"], ["Particule séparable", "particule + ge + radical"], ["Verbe en -ieren", "pas de ge-"]]) }),
      gp("separable-vs-inseparable", "Particules séparables et inséparables", "Les particules séparables se détachent dans la phrase principale et prennent ge- au Perfekt. Les préfixes inséparables comme ver-, be-, er-, ent-, emp-, ge-, miss-, zer- ne se détachent jamais et ne prennent pas ge- au Perfekt.", [["Ich rufe dich später an.", "Je t'appelle plus tard."], ["Ich verstehe die Frage.", "Je comprends la question."], ["Sie hat die Rechnung bezahlt.", "Elle a payé l'addition."]], "ver-, be- et er- ne se séparent pas et ne prennent pas ge- au Perfekt : verstanden, bezahlt, erklärt.", { table: tbl(["Type", "Présent", "Perfekt"], [["séparable", "Ich stehe auf.", "Ich bin aufgestanden."], ["inséparable", "Ich verstehe dich.", "Ich habe dich verstanden."], ["inséparable", "Er bezahlt.", "Er hat bezahlt."]]) }),
      gp("praeteritum-core", "Präteritum de sein, haben et des modaux", "À A2, le Präteritum est surtout indispensable pour sein, haben et les verbes modaux. Ces formes sont très fréquentes à l'écrit et aussi à l'oral.", [["Ich war gestern krank.", "J'étais malade hier."], ["Wir hatten keine Zeit.", "Nous n'avions pas le temps."], ["Sie musste arbeiten.", "Elle devait travailler."]], "Avec un modal au Präteritum, l'autre verbe reste infinitif à la fin : ich musste arbeiten.", { table: tbl(["Infinitif", "ich/er", "wir/sie"], [["sein", "war", "waren"], ["haben", "hatte", "hatten"], ["können", "konnte", "konnten"], ["müssen", "musste", "mussten"], ["wollen", "wollte", "wollten"]]) }),
      gp("subordinate-clauses", "Subordonnées avec weil, dass, wenn", "Avec weil, dass et wenn, le verbe conjugué va à la fin de la subordonnée. Si la subordonnée vient en premier, la principale commence ensuite par le verbe conjugué.", [["Ich bleibe zu Hause, weil ich krank bin.", "Je reste à la maison parce que je suis malade."], ["Wenn ich Zeit habe, koche ich.", "Si j'ai le temps, je cuisine."], ["Ich denke, dass Deutsch logisch ist.", "Je pense que l'allemand est logique."]], "wenn n'est pas le quand interrogatif : pour poser une question, utilise wann.", { table: tbl(["Mot", "Sens courant"], [["weil", "parce que"], ["dass", "que"], ["wenn", "si / quand habituel"]]) }),
      gp("indirect-questions", "Questions indirectes avec ob et W-Fragen", "Dans une question indirecte, le verbe conjugué va à la fin. ob introduit une question oui/non ; les mots en w restent utilisés pour les questions ouvertes.", [["Ich weiß nicht, ob er Zeit hat.", "Je ne sais pas s'il a le temps."], ["Kannst du mir sagen, wann der Zug fährt?", "Peux-tu me dire quand le train part ?"], ["Sie fragt, warum ich lerne.", "Elle demande pourquoi j'étudie."]], "Dans l'indirect, ne garde pas l'ordre de la question directe : ob er Zeit hat, pas ob hat er Zeit.", { table: tbl(["Direct", "Indirect"], [["Kommst du?", "Ich frage, ob du kommst."], ["Wann kommst du?", "Ich frage, wann du kommst."], ["Wo wohnst du?", "Ich weiß nicht, wo du wohnst."]]) }),
      gp("welcher-dieser", "welcher et dieser", "welcher signifie quel/lequel et sert à choisir. dieser signifie ce/cet/cette/ces et désigne quelque chose de précis. Les deux se déclinent comme des déterminants.", [["Welchen Film sehen wir?", "Quel film regardons-nous ?"], ["Diese Tasche ist schön.", "Ce sac est beau."], ["Mit welchem Bus fährst du?", "Avec quel bus pars-tu ?"]], "welcher et dieser changent selon le cas : welcher Film, welchen Film, mit welchem Film.", CASE_LINK),
      gp("comparison", "Comparatif et superlatif", "Le comparatif sert à comparer deux éléments. Le superlatif exprime le plus haut degré. Souvent : adjectif + -er, puis am + adjectif + -sten.", [["Berlin ist größer als Bonn.", "Berlin est plus grand que Bonn."], ["Dieses Zimmer ist kleiner.", "Cette chambre est plus petite."], ["Am besten lerne ich morgens.", "J'apprends le mieux le matin."]], "Pour dire plus ... que, l'allemand utilise als : größer als, schneller als.", { table: tbl(["Adjectif", "Comparatif", "Superlatif"], [["schnell", "schneller", "am schnellsten"], ["klein", "kleiner", "am kleinsten"], ["gut", "besser", "am besten"], ["viel", "mehr", "am meisten"]]) }),
      gp("reflexive-verbs", "Verbes réfléchis", "Un verbe réfléchi se construit avec un pronom qui renvoie au sujet : mich, dich, sich, uns, euch, sich. Certains sont réfléchis en allemand mais pas en français, ou inversement.", [["Ich freue mich.", "Je me réjouis."], ["Wir treffen uns um acht.", "Nous nous retrouvons à huit heures."], ["Sie interessiert sich für Musik.", "Elle s'intéresse à la musique."]], "Ne calque pas toujours le français : se souvenir = sich erinnern an, mais attendre = warten auf.", { table: tbl(["Sujet", "Pronom"], [["ich", "mich"], ["du", "dich"], ["er/sie/es", "sich"], ["wir", "uns"], ["ihr", "euch"], ["sie/Sie", "sich"]]) }),
      gp("dative-verbs-common", "Verbes courants avec datif", "Certains verbes prennent un complément au datif, même quand le français donne l'impression d'un COD. Apprends-les avec leur construction.", [["Kannst du mir helfen?", "Peux-tu m'aider ?"], ["Das Kleid gefällt ihr.", "La robe lui plaît."], ["Der Schlüssel gehört dem Nachbarn.", "La clé appartient au voisin."]], "helfen prend le datif : hilfst du mir, pas hilfst du mich.", { ...CASE_LINK, table: tbl(["Verbe", "Exemple"], [["helfen", "Ich helfe dir."], ["danken", "Ich danke Ihnen."], ["gefallen", "Das gefällt mir."], ["gehören", "Das gehört meinem Bruder."]]) }),
      gp("um-zu", "um ... zu + infinitif vs weil", "um ... zu exprime un but quand le sujet est le même dans les deux parties. weil exprime une cause ou une explication, pas un objectif.", [["Ich lerne Deutsch, um in Deutschland zu arbeiten.", "J'apprends l'allemand pour travailler en Allemagne."], ["Sie geht in den Supermarkt, um Brot zu kaufen.", "Elle va au supermarché pour acheter du pain."], ["Ich bleibe zu Hause, weil ich krank bin.", "Je reste à la maison parce que je suis malade."]], "Si le sujet change, um ... zu ne convient pas. Utilise plutôt damit À B1."),
      gp("polite-imperative", "Impératif de politesse et tournures polies", "Avec Sie, l'impératif garde le pronom après le verbe. Pour être plus diplomate, on utilise souvent könnten Sie ou würden Sie plutôt qu'un ordre direct.", [["Kommen Sie bitte herein.", "Entrez s'il vous plaît."], ["Könnten Sie mir bitte helfen?", "Pourriez-vous m'aider s'il vous plaît ?"], ["Würden Sie das bitte wiederholen?", "Voudriez-vous répéter cela s'il vous plaît ?"]], "öffnen Sie est correct mais direct ; könnten Sie öffnen est souvent plus poli."),
      gp("fixed-prepositions", "Verbes avec prépositions fixes", "Certains verbes appellent une préposition précise. Il faut apprendre le verbe avec sa préposition comme une unité, car la préposition ne se déduit pas toujours du français.", [["Ich warte auf den Bus.", "J'attends le bus."], ["Denkst du an mich?", "Penses-tu à moi ?"], ["Ich freue mich über dein Geschenk.", "Je suis content de ton cadeau."]], "La préposition allemande ne copie pas toujours le français : warten auf, pas warten für.", { ...CASE_LINK, table: tbl(["Expression", "Sens"], [["warten auf", "attendre"], ["denken an", "penser à"], ["sich freuen auf", "se réjouir à l'avance de"], ["sich freuen über", "être content de quelque chose déjà présent/passé"]]) }),
      gp("tekamolo-basic", "Date et ordre des compléments de temps", "Pour raconter une journée ou fixer un rendez-vous, l'allemand place souvent le complément de temps tôt dans la phrase. La date ou le moment peut ouvrir la phrase, mais le verbe reste en deuxième position ; dans le Mittelfeld, retiens la tendance temps - manière - lieu.", [["Ich fahre morgen mit dem Zug nach Berlin.", "Je vais demain en train à Berlin."], ["Wir lernen heute zusammen in der Bibliothek.", "Nous étudions aujourd'hui ensemble à la bibliothèque."], ["Am Samstag gehe ich mit Freunden ins Kino.", "Samedi, je vais au cinéma avec des amis."]], "Le verbe conjugué reste en deuxième position, même si le temps est en premier : Am Samstag gehe ich."),
      gp("future-werden-present", "Futur avec werden vs présent + morgen", "Le futur peut se former avec werden + infinitif, mais le présent avec un marqueur de temps est très courant pour parler d'un futur proche ou prévu.", [["Morgen gehe ich zum Arzt.", "Demain, je vais chez le médecin."], ["Ich werde morgen lernen.", "J'étudierai demain."], ["Wir besuchen nächste Woche unsere Freunde.", "Nous rendons visite à nos amis la semaine prochaine."]], "werden donne souvent un ton plus formel, une prédiction ou une intention formulée comme futur."),
      gp("als-wenn-past-first", "als vs wenn au passé : première approche", "Pour un événement unique dans le passé, on utilise als. Pour une répétition ou une condition, on utilise wenn. À A2, retiens surtout als = quand une fois dans le passé.", [["Als ich ein Kind war, wohnte ich in Paris.", "Quand j'étais enfant, j'habitais à Paris."], ["Wenn ich Ferien hatte, besuchte ich meine Oma.", "Quand j'avais des vacances, je rendais visite à ma grand-mère."], ["Wenn ich Zeit habe, komme ich.", "Si j'ai le temps, je viens."]], "als ne sert pas pour une condition actuelle. Pour si j'ai le temps, dis wenn ich Zeit habe."),
      gp("sequence-connectors", "zuerst, dann, danach, zum Schluss", "Ces connecteurs organisent un récit ou une procédure. Quand ils sont en première position, le verbe conjugué arrive juste après.", [["Zuerst frühstücke ich.", "D'abord, je prends le petit-déjeuner."], ["Dann fahre ich zur Arbeit.", "Ensuite, je vais au travail."], ["Zum Schluss räume ich die Küche auf.", "Pour finir, je range la cuisine."]], "Après dann ou danach en position 1, on inverse : Dann fahre ich, pas Dann ich fahre.")
    ]
  },

  {
    level: "B1",
    points: [
      gp("praeteritum-general", "Le Präteritum général", "Au B1, on rencontre davantage le Präteritum des verbes courants, surtout dans les récits, articles et biographies. à l'oral, le Perfekt reste fréquent, sauf avec sein, haben et les modaux.", [["Er ging nach Hause.", "Il rentra / est rentré à la maison."], ["Sie kam spät an.", "Elle arriva tard."], ["Der Film begann um acht Uhr.", "Le film commença à huit heures."]], "Ne remplace pas tout le Perfekt oral par le Präteritum : le registre change selon le verbe et le contexte."),
      gp("als-wenn-wann", "als, wenn, wann : récapitulatif complet", "wann sert dans les questions directes ou indirectes. wenn sert pour si, pour quand répété ou futur. als sert pour un événement unique dans le passé.", [["Wann kommst du?", "Quand viens-tu ?"], ["Wenn ich Zeit habe, rufe ich dich an.", "Si j'ai le temps, je t'appelle."], ["Als ich in Berlin war, besuchte ich ein Museum.", "Quand j'étais à Berlin, j'ai visité un musée."]], "wenn n'est pas quand interrogatif. Dis Ich weiß nicht, wann er kommt, pas wenn er kommt.", { table: tbl(["Mot", "Usage"], [["wann", "question : quand ?"], ["wenn", "si / quand répété ou futur"], ["als", "quand unique dans le passé"]]) }),
      gp("plusquamperfekt", "Plusquamperfekt : hatte/war + participe", "Le Plusquamperfekt exprime une action antérieure à une autre action passée. Il se forme avec hatte ou war + participe passé, selon le même choix que le Perfekt.", [["Ich hatte schon gegessen, als sie ankam.", "J'avais déjà mangé quand elle est arrivée."], ["Er war nach Hause gegangen, bevor ich kam.", "Il était rentré chez lui avant que j'arrive."], ["Wir hatten den Film gesehen.", "Nous avions vu le film."]], "Ne l'utilise pas pour tout passé lointain : il sert surtout à marquer avant une autre action passée."),
      gp("konjunktiv-ii", "Konjunktiv II poli et hypothétique", "Le Konjunktiv II sert à être poli, à exprimer un souhait ou une hypothèse. Les formes fréquentes sont würde + infinitif, hätte, wäre, könnte.", [["Ich hätte gern einen Kaffee.", "Je voudrais un café."], ["Könnten Sie mir helfen?", "Pourriez-vous m'aider ?"], ["Wenn ich Zeit hätte, würde ich mehr lesen.", "Si j'avais le temps, je lirais davantage."]], "Avec sein, haben et les modaux, les formes wäre, hätte, könnte sont souvent préférées à würde sein/haben/können."),
      gp("konjunktiv-ii-past", "Konjunktiv II passé", "Pour parler d'une hypothèse irréelle dans le passé, on utilise hätte ou wäre + participe passé. Cela correspond souvent à j'aurais fait ou je serais allé.", [["Ich hätte mehr lernen sollen.", "J'aurais dû étudier davantage."], ["Wenn ich Zeit gehabt hätte, wäre ich gekommen.", "Si j'avais eu le temps, je serais venu."], ["Sie wäre gern geblieben.", "Elle serait volontiers restée."]], "Ne traduis pas j'aurais par würde haben : on dit ich hätte gemacht."),
      gp("zu-infinitive", "zu + infinitif", "zu + infinitif complète de nombreux verbes, noms et expressions : versuchen zu, Lust haben zu, es ist wichtig zu. Avec les verbes séparables, zu se place entre la particule et le verbe.", [["Ich versuche, jeden Tag Deutsch zu lernen.", "J'essaie d'apprendre l'allemand chaque jour."], ["Hast du Lust, ins Kino zu gehen?", "As-tu envie d'aller au cinéma ?"], ["Es ist wichtig, früh aufzustehen.", "Il est important de se lever tôt."]], "Après un modal, pas de zu : ich muss lernen, pas ich muss zu lernen."),
      gp("brauchen-zu", "brauchen nicht/nur zu", "brauchen + zu fonctionne surtout avec nicht ou nur et signifie ne pas avoir besoin de / il suffit de. Sans négation ou restriction, on préfère souvent müssen ou sollen.", [["Du brauchst nicht zu kommen.", "Tu n'as pas besoin de venir."], ["Sie brauchen nur hier zu unterschreiben.", "Vous avez seulement besoin de signer ici."], ["Ich brauche das nicht zu erklären.", "Je n'ai pas besoin d'expliquer cela."]], "Ne dis pas simplement ich brauche kommen. Dans cette construction, il faut zu."),
      gp("relative-clauses", "Les relatives", "Une relative donne une information sur un nom. Le pronom relatif ressemble à der/die/das, mais son cas dépend de son rôle dans la relative.", [["Das ist der Mann, der hier wohnt.", "C'est l'homme qui habite ici."], ["Das ist die Frau, die ich kenne.", "C'est la femme que je connais."], ["Das ist das Kind, dem ich helfe.", "C'est l'enfant que j'aide / à qui j'aide."]], "Le pronom relatif dépend de sa fonction dans la subordonnée, pas seulement du nom en français.", CASE_LINK),
      gp("relative-preposition", "Relatives avec préposition", "Quand une préposition appartient à la relative, elle se place avant le pronom relatif. Le cas du pronom dépend de la préposition.", [["Das ist der Mann, mit dem ich spreche.", "C'est l'homme avec qui je parle."], ["Die Stadt, in der ich wohne, ist groß.", "La ville dans laquelle j'habite est grande."], ["Das Thema, über das wir sprechen, ist wichtig.", "Le sujet dont nous parlons est important."]], "Ne laisse pas la préposition à la fin comme en français oral : mit dem, über das.", CASE_LINK),
      gp("pronominal-adverbs", "Adverbes pronominaux : darauf, damit, worauf", "Avec une préposition + chose/idée, l'allemand utilise souvent da- ou wo- : damit, darauf, worauf, womit. Pour une personne, on garde préposition + pronom.", [["Ich freue mich darauf.", "Je m'en réjouis."], ["Womit beschäftigst du dich?", "De quoi t'occupes-tu ?"], ["Darüber sprechen wir morgen.", "Nous en parlerons demain."]], "Pour une personne, ne dis pas damit : mit ihr, mit ihm, pas damit.", { table: tbl(["Question", "Réponse"], [["Worauf wartest du?", "Ich warte darauf."], ["Womit schreibst du?", "Ich schreibe damit."], ["Mit wem sprichst du?", "Mit Anna."]]) }),
      gp("passive", "Le passif présent et passé", "Le passif met l'action au centre plutôt que la personne qui agit. Il se forme avec werden + participe passé. Au passé composé : ist/sein + participe + worden.", [["Das Auto wird repariert.", "La voiture est réparée / en cours de réparation."], ["Das Haus ist 1990 gebaut worden.", "La maison a été construite en 1990."], ["Die E-Mail wurde gestern geschrieben.", "L'e-mail a été écrite hier."]], "Ne confonds pas werden futur et werden passif : le participe passé signale le passif."),
      gp("passive-modal", "Passif avec verbes modaux", "Avec un modal, le passif garde werden à l'infinitif en fin de groupe verbal. La structure exprime ce qui doit, peut ou devrait être fait.", [["Das Formular muss ausgefüllt werden.", "Le formulaire doit être rempli."], ["Die Rechnung kann online bezahlt werden.", "La facture peut être payée en ligne."], ["Der Text sollte korrigiert werden.", "Le texte devrait être corrigé."]], "Ne supprime pas werden : muss gemacht werden, pas muss gemacht."),
      gp("connectors-b1", "deshalb, trotzdem, obwohl", "Ces connecteurs expriment conséquence ou opposition. deshalb et trotzdem occupent une position dans la phrase principale ; obwohl introduit une subordonnée avec verbe à la fin.", [["Ich bin krank, deshalb bleibe ich zu Hause.", "Je suis malade, donc je reste à la maison."], ["Es regnet, trotzdem gehen wir spazieren.", "Il pleut, malgré cela nous allons nous promener."], ["Obwohl ich müde bin, lerne ich Deutsch.", "Bien que je sois fatigué, j'apprends l'allemand."]], "obwohl fonctionne comme weil pour la place du verbe : verbe conjugué à la fin de la subordonnée.", { table: tbl(["Connecteur", "Sens", "Position du verbe"], [["deshalb", "donc", "verbe juste après"], ["trotzdem", "malgré cela", "verbe juste après"], ["obwohl", "bien que", "verbe à la fin"]]) }),
      gp("genitive-prepositions-common", "Prépositions courantes avec génitif", "wegen, trotz et während prennent souvent le génitif dans la langue standard écrite. à l'oral, on entend parfois le datif, mais pour un allemand soigné, apprends le génitif.", [["Wegen des Wetters bleiben wir zu Hause.", "À cause du temps, nous restons à la maison."], ["Trotz des Regens gehen wir spazieren.", "Malgré la pluie, nous allons nous promener."], ["Während der Ferien arbeite ich nicht.", "Pendant les vacances, je ne travaille pas."]], "Ne calque pas toujours à cause de + datif : wegen des Wetters est la forme standard.", CASE_LINK),
      gp("je-desto", "je ... desto", "je ... desto exprime une proportion : plus X, plus Y. La partie avec je est subordonnée ; la partie avec desto déclenche souvent l'inversion.", [["Je mehr ich übe, desto besser spreche ich.", "Plus je pratique, mieux je parle."], ["Je früher wir anfangen, desto schneller sind wir fertig.", "Plus tôt nous commençons, plus vite nous avons fini."], ["Je länger ich lerne, desto sicherer werde ich.", "Plus j'étudie longtemps, plus je deviens sûr de moi."]], "Ne mets pas desto seul au début d'une phrase normale : il répond à je."),
      gp("adjectives-as-nouns", "Adjectifs substantivés", "Un adjectif peut devenir un nom : der Deutsche, die Kranke, etwas Neues. Il garde alors des terminaisons d'adjectif selon l'article, le genre, le nombre et le cas.", [["Der Deutsche spricht schnell.", "L'Allemand parle vite."], ["Ich habe etwas Neues gelernt.", "J'ai appris quelque chose de nouveau."], ["Viele Jugendliche nutzen soziale Medien.", "Beaucoup de jeunes utilisent les réseaux sociaux."]], "Ne laisse pas l'adjectif sans terminaison : etwas Neues, pas etwas Neu.", CASE_LINK),
      gp("n-declension", "Déclinaison en -n des noms faibles", "Certains noms masculins prennent -n ou -en à toutes les formes sauf le nominatif singulier. Beaucoup désignent des personnes ou des êtres vivants.", [["Ich sehe den Nachbarn.", "Je vois le voisin."], ["Ich helfe dem Studenten.", "J'aide l'étudiant."], ["Die Nummer des Kunden fehlt.", "Le numéro du client manque."]], "C'est un point lié aux cas : nominatif der Student, mais accusatif den Studenten.", { ...CASE_LINK, table: tbl(["Nominatif", "Autres formes fréquentes"], [["der Nachbar", "den/dem/des Nachbarn"], ["der Student", "den/dem/des Studenten"], ["der Kunde", "den/dem/des Kunden"]]) }),
      gp("lassen-infinitive", "lassen + infinitif", "lassen + infinitif peut signifier laisser faire, faire faire, ou permettre qu'une action se produise. L'infinitif reste à la fin.", [["Ich lasse mein Auto reparieren.", "Je fais réparer ma voiture."], ["Lass mich schlafen!", "Laisse-moi dormir !"], ["Sie lässt sich die Haare schneiden.", "Elle se fait couper les cheveux."]], "Ne traduis pas toujours par laisser : Ich lasse mein Auto reparieren = je fais réparer ma voiture."),
      gp("seit-vor-time", "seit / vor + datif pour le temps", "seit indique une durée qui continue jusqu'à maintenant. vor indique un moment dans le passé. Ces prépositions prennent le datif.", [["Ich lerne seit zwei Jahren Deutsch.", "J'apprends l'allemand depuis deux ans."], ["Ich habe vor zwei Jahren angefangen.", "J'ai commencé il y a deux ans."], ["Vor einer Woche war ich in Berlin.", "Il y a une semaine, j'étais à Berlin."]], "seit = depuis et continue encore ; vor = il y a.", CASE_LINK),
      gp("damit-um-zu", "damit vs um ... zu", "Les deux peuvent exprimer un but. um ... zu s'utilise si le sujet est le même. damit s'utilise notamment quand le sujet change.", [["Ich lerne Deutsch, um in Deutschland zu arbeiten.", "J'apprends l'allemand pour travailler en Allemagne."], ["Ich spreche langsam, damit du mich verstehst.", "Je parle lentement pour que tu me comprennes."], ["Ich öffne das Fenster, damit frische Luft hereinkommt.", "J'ouvre la fenêtre pour que l'air frais entre."]], "Avec damit, le verbe conjugué va à la fin : damit du mich verstehst."),
      gp("indirect-speech-simple", "Discours indirect simple", "Au B1, le discours indirect peut être exprimé simplement avec dass, surtout à l'oral. Le Konjunktiv I est plus avancé et plus journalistique.", [["Er sagt, dass er krank ist.", "Il dit qu'il est malade."], ["Sie meint, dass der Termin wichtig ist.", "Elle pense que le rendez-vous est important."], ["Der Lehrer sagt, wir sollen üben.", "Le professeur dit que nous devons pratiquer."]], "Avec dass, le verbe va à la fin : dass er krank ist, pas dass er ist krank.")
    ]
  },

  {
    level: "B2",
    points: [
      gp("konjunktiv-i-reported-speech", "Konjunktiv I et discours indirect de presse", "Le Konjunktiv I marque que l'information est rapportée, surtout dans les articles et comptes rendus. Il évite de présenter les propos comme une certitude de l'auteur.", [["Der Minister sagte, die Lage sei ernst.", "Le ministre a déclaré que la situation était sérieuse."], ["Die Zeitung berichtet, der Täter habe gestanden.", "Le journal rapporte que l'auteur aurait avoué."], ["Sie erklärte, sie könne nicht teilnehmen.", "Elle a expliqué qu'elle ne pouvait pas participer."]], "À l'oral quotidien, on utilise souvent dass + indicatif ; le Konjunktiv I est surtout presse, administratif ou soutenu.", { table: tbl(["Direct", "Indirect"], [["Er ist krank.", "Er sei krank."], ["Sie hat keine Zeit.", "Sie habe keine Zeit."], ["Wir kommen morgen.", "Sie kämen morgen."]]) }),
      gp("zustandspassiv", "Passif d'état vs passif d'action", "Le passif d'action avec werden décrit un processus. Le passif d'état avec sein décrit le résultat après l'action. La différence est importante pour éviter l'ambiguïté.", [["Das Geschäft ist geschlossen.", "Le magasin est fermé."], ["Das Geschäft wird um acht geschlossen.", "Le magasin est fermé à huit heures."], ["Der Computer ist repariert.", "L'ordinateur est réparé."]], "sein + participe n'est pas toujours un passé composé : ist geöffnet décrit un état.", { table: tbl(["Forme", "Sens"], [["Die Tür wird geöffnet.", "On ouvre la porte."], ["Die Tür ist geöffnet.", "La porte est ouverte."], ["Das Fenster wurde geschlossen.", "On a fermé la fenêtre."], ["Das Fenster war geschlossen.", "La fenêtre était fermée."]]) }),
      gp("participles-as-adjectives", "Participes I et II comme adjectifs", "Le participe I exprime une action en cours ou active. Le participe II exprime souvent un résultat ou une idée passive. Comme adjectifs, ils prennent des terminaisons.", [["Das lachende Kind spielt im Garten.", "L'enfant qui rit joue dans le jardin."], ["Das geschriebene Buch liegt auf dem Tisch.", "Le livre écrit est sur la table."], ["Die geöffneten Fenster bleiben offen.", "Les fenêtres ouvertes restent ouvertes."]], "Ne confonds pas lachend = qui rit et gelacht = ri. Le sens actif/passif change.", CASE_LINK),
      gp("participial-constructions", "Constructions participiales", "Les constructions participiales condensent une relative ou une proposition. Elles sont fréquentes à l'écrit, mais trop lourdes à l'oral si on les accumule.", [["Die seit Jahren bestehende Regel wurde geändert.", "La règle qui existait depuis des années a été modifiée."], ["Die im Vertrag genannten Bedingungen gelten weiterhin.", "Les conditions mentionnées dans le contrat restent valables."], ["Der gestern veröffentlichte Bericht sorgt für Diskussionen.", "Le rapport publié hier suscite des discussions."]], "Si la phrase devient illisible, préfère une relative avec der/die/das."),
      gp("nominalization", "Nominalisation : Verbalstil vers Nominalstil", "Le style nominal transforme une action en nom ou groupe nominal. Il est fréquent dans les textes administratifs, universitaires et journalistiques, mais peut devenir lourd.", [["Beim Lesen lerne ich neue Wörter.", "En lisant, j'apprends de nouveaux mots."], ["Nach der Ankunft rief sie ihre Eltern an.", "Après l'arrivée, elle a appelé ses parents."], ["Wegen des Umbaus bleibt das Büro geschlossen.", "En raison des travaux, le bureau reste fermé."]], "Le style nominal est utile à l'écrit, mais à l'oral il peut sonner artificiel.", { ...CASE_LINK, table: tbl(["Verbalstil", "Nominalstil"], [["wenn man liest", "beim Lesen"], ["nachdem sie angekommen ist", "nach der Ankunft"], ["weil die Preise steigen", "wegen des Preisanstiegs"]]) }),
      gp("modal-past-irrealis", "Modaux au passé irréel", "Pour dire aurait pu, aurait dû, aurait voulu faire, l'allemand combine hätte + infinitif lexical + modal à l'infinitif. C'est une structure longue mais très fréquente À B2.", [["Ich hätte früher gehen können.", "J'aurais pu partir plus tôt."], ["Du hättest das sagen müssen.", "Tu aurais dû dire cela."], ["Wir hätten länger bleiben wollen.", "Nous aurions voulu rester plus longtemps."]], "Le modal reste à l'infinitif final : hätte machen können, pas hätte gekonnt machen."),
      gp("sich-lassen-infinitive", "sich lassen + infinitif", "sich lassen + infinitif exprime souvent la possibilité passive : cela peut se faire, cela se lit facilement. C'est plus élégant que man kann dans certains contextes.", [["Das lässt sich machen.", "Cela peut se faire."], ["Der Text lässt sich leicht verstehen.", "Le texte se comprend facilement."], ["Das Problem lässt sich nicht schnell lösen.", "Le problème ne peut pas se résoudre rapidement."]], "Cette structure concerne souvent une chose, pas une personne qui se laisse faire."),
      gp("scheinen-drohen-pflegen-zu", "scheinen, drohen, pflegen + zu", "Ces verbes introduisent une nuance : scheinen = sembler, drohen = risquer de, pflegen = avoir l'habitude de dans un style soutenu. Ils se construisent avec zu + infinitif.", [["Er scheint krank zu sein.", "Il semble être malade."], ["Die Lage droht sich zu verschlechtern.", "La situation risque de se détériorer."], ["Sie pflegt früh aufzustehen.", "Elle a l'habitude de se lever tôt."]], "pflegen + zu est soutenu ; à l'oral, on dira souvent gewöhnlich ou normalerweise."),
      gp("advanced-connectors-families", "Connecteurs avancés par familles", "À B2, les connecteurs servent à structurer un raisonnement. Certains occupent une position dans la phrase principale et déclenchent l'inversion ; d'autres introduisent une subordonnée.", [["Die Kosten sind hoch, dennoch lohnt sich das Projekt.", "Les coûts sont élevés, pourtant le projet vaut la peine."], ["Die Nachfrage steigt; folglich müssen wir mehr produzieren.", "La demande augmente ; par conséquent, nous devons produire davantage."], ["Er ist erfahren, allerdings fehlt ihm Zeit.", "Il est expérimenté, toutefois il lui manque du temps."]], "Après dennoch ou folglich en position 1, le verbe vient juste après : dennoch lohnt es sich.", { table: tbl(["Famille", "Connecteurs"], [["opposition", "hingegen, allerdings, dennoch"], ["conséquence", "folglich, somit, infolgedessen"], ["concession", "gleichwohl, obwohl, auch wenn"]]) }),
      gp("correlative-connectors", "Corrélatifs : sowohl... als auch, weder... noch", "Les corrélatifs relient deux éléments de même niveau. Ils sont utiles pour écrire plus précisément, mais demandent une structure parallèle.", [["Sie spricht sowohl Deutsch als auch Englisch.", "Elle parle aussi bien allemand qu'anglais."], ["Ich habe weder Zeit noch Geld.", "Je n'ai ni temps ni argent."], ["Das ist zwar teuer, aber sehr nützlich.", "C'est certes cher, mais très utile."]], "Garde des éléments parallèles : weder heute noch morgen, pas une moitié phrase et une moitié nom.", { table: tbl(["Corrélatif", "Sens"], [["sowohl ... als auch", "aussi bien ... que"], ["weder ... noch", "ni ... ni"], ["entweder ... oder", "soit ... soit"], ["zwar ... aber", "certes ... mais"], ["nicht nur ... sondern auch", "non seulement ... mais aussi"]]) }),
      gp("extended-genitive-prepositions", "Prépositions étendues avec génitif", "Les textes B2 utilisent souvent des prépositions au génitif : anhand, aufgrund, bezüglich, infolge, mangels, angesichts. Elles condensent une relation logique en peu de mots.", [["Anhand der Daten kann man den Trend erkennen.", "À partir des données, on peut reconnaître la tendance."], ["Aufgrund des Streiks fallen viele Züge aus.", "En raison de la grève, de nombreux trains sont annulés."], ["Angesichts der Lage müssen wir handeln.", "Compte tenu de la situation, nous devons agir."]], "Ces formes sont surtout écrites ou soutenues ; à l'oral, des tournures plus simples sont souvent préférées.", CASE_LINK),
      gp("sodass-so-dass", "sodass vs so ... dass", "sodass introduit une conséquence : si bien que. so ... dass insiste sur l'intensité : tellement ... que. Dans les deux cas, le verbe de la subordonnée va à la fin.", [["Es regnete stark, sodass wir zu Hause blieben.", "Il pleuvait fort, si bien que nous sommes restés à la maison."], ["Es war so kalt, dass der See zufror.", "Il faisait si froid que le lac a gelé."], ["Sie sprach so leise, dass ich sie kaum verstand.", "Elle parlait si doucement que je la comprenais à peine."]], "sodass = conséquence globale ; so ... dass = degré ou intensité."),
      gp("funktionsverbgefuege", "Funktionsverbgefüge courants", "Ces groupes verbe + nom sont fréquents dans le style administratif et professionnel. Le verbe porte peu de sens ; le nom porte l'idée principale.", [["Wir müssen eine Entscheidung treffen.", "Nous devons prendre une décision."], ["Die Räume stehen zur Verfügung.", "Les salles sont disponibles."], ["Diese Lösung kommt nicht in Frage.", "Cette solution n'entre pas en ligne de compte."]], "Ne traduis pas mot à mot : zur Verfügung stehen veut dire être disponible.", { table: tbl(["Expression", "Sens simple"], [["eine Entscheidung treffen", "entscheiden"], ["zur Verfügung stehen", "verfügbar sein"], ["in Frage kommen", "möglich sein"], ["eine Rolle spielen", "wichtig sein"]]) }),
      gp("mittelfeld-word-order", "Ordre des mots dans le Mittelfeld", "Entre le verbe conjugué et la fin verbale, l'allemand organise les compléments. En tendance, les pronoms viennent avant les noms ; connu avant nouveau ; datif avant accusatif si les deux sont des noms.", [["Ich gebe dem Kind den Ball.", "Je donne le ballon à l'enfant."], ["Ich gebe ihn dem Kind.", "Je le donne à l'enfant."], ["Heute hat sie es mir erklärt.", "Aujourd'hui, elle me l'a expliqué."]], "Il existe des variations selon l'information mise en valeur ; n'en fais pas une formule mécanique absolue.", { ...CASE_LINK, table: tbl(["Tendance", "Exemple"], [["pronom avant nom", "Ich gebe ihm das Buch."], ["accusatif pronom avant datif nom", "Ich gebe es dem Lehrer."], ["temps avant lieu", "Ich fahre morgen nach Berlin."]]) })
    ]
  },
  {
    level: "C1",
    points: [
      gp("subjective-modals", "Valeur subjective des verbes modaux", "À C1, les modaux peuvent exprimer une source ou une probabilité, pas seulement une obligation. sollen rapporte une rumeur, dürfte exprime une forte probabilité, wollen rapporte une affirmation du sujet.", [["Die Firma soll verkauft werden.", "On dit que l'entreprise va être vendue."], ["Das dürfte kein Problem sein.", "Cela ne devrait probablement pas poser problème."], ["Sie will nichts davon gewusst haben.", "Elle prétend n'en avoir rien su."]], "Ne lis pas sollen uniquement comme devoir : Er soll reich sein ne veut pas dire il doit être riche.", { table: tbl(["Forme", "Nuance"], [["Er soll reich sein.", "On dit qu'il est riche."], ["Er dürfte zu Hause sein.", "Il est probablement chez lui."], ["Er will es gesehen haben.", "Il prétend l'avoir vu."]]) }),
      gp("future-ii-supposition", "Futur II pour la supposition", "Le Futur II peut exprimer une supposition sur un événement terminé : il aura probablement oublié. Il se forme avec werden + participe + haben/sein.", [["Er wird es vergessen haben.", "Il l'aura probablement oublié."], ["Sie wird schon angekommen sein.", "Elle sera sûrement déjà arrivée."], ["Du wirst davon gehört haben.", "Tu en as sûrement entendu parler."]], "Ce n'est pas seulement un futur chronologique ; c'est souvent une hypothèse sur le passé."),
      gp("bekommen-passive", "Passif avec bekommen", "Le passif avec bekommen met le bénéficiaire au centre. Il correspond souvent à se voir offrir/donner/remettre quelque chose. On l'appelle aussi Rezipientenpassiv.", [["Er bekommt das Buch geschenkt.", "Il reçoit le livre en cadeau."], ["Sie bekam die Stelle angeboten.", "On lui a proposé le poste."], ["Ich bekomme den Termin bestätigt.", "On me confirme le rendez-vous."]], "Ce n'est pas le passif standard avec werden : ici, le destinataire devient sujet."),
      gp("modalpartikeln", "Modalpartikeln : doch, ja, eben, halt, mal, schon, wohl", "Les particules modales nuancent l'attitude du locuteur : rappel, évidence, impatience, douceur, résignation, supposition. Elles sont très fréquentes à l'oral et difficiles à traduire.", [["Komm doch mit!", "Viens donc avec nous !"], ["Das ist ja interessant.", "Tiens, c'est intéressant."], ["Kannst du mal helfen?", "Tu peux aider un instant ?"]], "Ne les traduis pas mot à mot. Leur effet dépend du ton, du contexte et de la relation entre les personnes.", { table: tbl(["Particule", "Nuance fréquente"], [["doch", "rappel, contradiction douce"], ["ja", "évidence partagée"], ["eben/halt", "résignation : c'est comme ça"], ["mal", "adoucit une demande"], ["schon", "rassure ou concède"], ["wohl", "probabilité"]]) }),
      gp("elevated-connectors-c1", "Connecteurs soutenus", "indes, zumal, sofern, es sei denn et geschweige denn structurent un raisonnement soutenu. Ils sont utiles dans les textes argumentatifs, mais peuvent paraître trop formels à l'oral quotidien.", [["Das Projekt ist teuer, indes notwendig.", "Le projet est coûteux, néanmoins nécessaire."], ["Wir fahren, sofern das Wetter gut bleibt.", "Nous partons à condition que le temps reste bon."], ["Er kann kaum lesen, geschweige denn einen Vertrag verstehen.", "Il sait à peine lire, sans même parler de comprendre un contrat."]], "Ces connecteurs sont puissants mais marqués ; dans une conversation simple, préfère jedoch, weil ou wenn.", { table: tbl(["Connecteur", "Sens"], [["indes", "cependant, néanmoins"], ["zumal", "d'autant plus que"], ["sofern", "à condition que"], ["es sei denn", "à moins que"], ["geschweige denn", "sans même parler de"]]) }),
      gp("ausklammerung-stylistic-order", "Ausklammerung et variations stylistiques", "L'Ausklammerung place un élément après le cadre verbal pour alléger ou mettre en valeur. C'est fréquent avec des groupes longs, mais à utiliser avec contrôle.", [["Er hat angerufen wegen des Termins morgen.", "Il a appelé au sujet du rendez-vous de demain."], ["Ich habe nicht gerechnet mit einer so schnellen Antwort.", "Je ne m'attendais pas à une réponse aussi rapide."], ["Sie ist stolz auf das, was sie erreicht hat.", "Elle est fière de ce qu'elle a accompli."]], "N'utilise pas l'Ausklammerung pour éviter l'ordre normal quand la phrase est simple."),
      gp("genitive-chains-nominal-style", "Chaînes de génitifs et style nominal soutenu", "Le style soutenu accumule parfois des groupes nominaux et des génitifs. Cela permet une forte densité d'information, mais peut devenir lourd si la phrase n'est pas bien structurée.", [["Die Folgen der Entscheidung des Gerichts sind weitreichend.", "Les conséquences de la décision du tribunal sont considérables."], ["Die Umsetzung der Maßnahmen der Regierung beginnt sofort.", "La mise en oeuvre des mesures du gouvernement commence immédiatement."], ["Während der Prüfung der Unterlagen wurden Fehler entdeckt.", "Pendant l'examen des documents, des erreurs ont été découvertes."]], "Trop de génitifs rendent la phrase opaque ; une relative ou une phrase verbale peut être plus claire.", CASE_LINK),
      gp("extended-infinitive-clauses", "Constructions infinitives étendues", "um ... zu exprime un but, ohne ... zu une absence d'action, anstatt ... zu une alternative non choisie. Ces structures partagent souvent le même sujet que la principale.", [["Sie spart Geld, um später zu studieren.", "Elle économise de l'argent pour étudier plus tard."], ["Er ging, ohne sich zu verabschieden.", "Il est parti sans dire au revoir."], ["Anstatt zu warten, rief sie direkt an.", "Au lieu d'attendre, elle a appelé directement."]], "Si le sujet change, ces infinitives ne conviennent pas toujours ; utilise une subordonnée complète."),
      gp("condition-without-wenn", "Condition sans wenn", "Dans un style plus soutenu ou concis, une condition peut commencer directement par le verbe conjugué au Konjunktiv II. Le sens reste si..., mais wenn disparaît.", [["Hätte ich Zeit, würde ich mitkommen.", "Si j'avais le temps, je viendrais avec vous."], ["Wäre das Wetter besser, gingen wir spazieren.", "Si le temps était meilleur, nous irions nous promener."], ["Sollten Sie Fragen haben, melden Sie sich bitte.", "Si vous avez des questions, contactez-nous."]], "Cette structure est plus formelle ; à l'oral simple, wenn ich Zeit hätte reste très naturel."),
      gp("anticipatory-es", "Anticipation avec es", "es peut annoncer une subordonnée ou un infinitif qui vient plus tard. Cela permet de placer une évaluation au début : Es freut mich, dass...", [["Es freut mich, dass du gekommen bist.", "Je suis heureux que tu sois venu."], ["Es ist wichtig, regelmäßig zu üben.", "Il est important de pratiquer régulièrement."], ["Es überrascht mich, wie schnell du lernst.", "Cela me surprend à quelle vitesse tu apprends."]], "Ne traduis pas toujours es par cela ; il sert souvent de support grammatical."),
      gp("registers-overview", "Registres : familier, standard, soutenu", "Au C1, il faut choisir le niveau de langue selon la situation. Une tournure familière peut être parfaite avec des amis, mais déplacée dans un courrier professionnel ; une tournure soutenue peut sembler lourde à l'oral.", [["Das kriegen wir schon hin.", "On va bien y arriver."], ["Das können wir schaffen.", "Nous pouvons y arriver."], ["Dies lässt sich realisieren.", "Cela peut être réalisé."]], "Ne mélange pas sans raison familier et soutenu dans le même texte : le registre doit rester cohérent.", { table: tbl(["Registre", "Exemple"], [["familier", "Kriegen wir das hin?"], ["standard", "Schaffen wir das?"], ["soutenu", "Lässt sich das realisieren?"]]) })
    ]
  }
];
