"use strict";

const GRAMMAR_CASES = {
  intro: "En allemand, l'article change selon le rôle du mot dans la phrase. Pour débuter, les 3 cas essentiels sont : nominatif, accusatif et datif.",
  genitiveNote: "Le génitif existe, mais tu peux le laisser pour plus tard.",
  accusativeNote: "À l'accusatif, seul le masculin change : der devient den.",
  mixedRule: "Prépositions mixtes : datif = position. Accusatif = mouvement.",
  definedArticles: [
    ["Nominatif", "der", "die", "das", "die"],
    ["Accusatif", "den", "die", "das", "die"],
    ["Datif", "dem", "der", "dem", "den (+n)"],
  ],
  indefiniteArticles: [
    ["Nominatif", "ein", "eine", "ein"],
    ["Accusatif", "einen", "eine", "ein"],
    ["Datif", "einem", "einer", "einem"],
  ],
  caseCards: [
    { title: "Nominatif = sujet", example: "Der Hund schläft.", fr: "Le chien dort." },
    { title: "Accusatif = COD", example: "Ich sehe den Hund.", fr: "Je vois le chien." },
    { title: "Datif = COI / à qui ?", example: "Ich helfe dem Mann.", fr: "J'aide l'homme." },
  ],
  prepositions: [
    { title: "Toujours datif", items: ["aus", "bei", "mit", "nach", "seit", "von", "zu"] },
    { title: "Toujours accusatif", items: ["durch", "für", "gegen", "ohne", "um"] },
    { title: "Prépositions mixtes", items: ["in", "an", "auf", "über", "unter", "vor", "hinter", "neben", "zwischen"] },
  ],
  mixedExamples: [
    { de: "Ich bin in der Stadt.", fr: "Je suis en ville." },
    { de: "Ich gehe in die Stadt.", fr: "Je vais en ville." },
  ],
  dativeVerbs: ["helfen", "danken", "gefallen", "gehören", "antworten"],
  dativeVerbExample: { de: "Kannst du mir helfen?", fr: "Peux-tu m'aider ?" },
  pronouns: [
    ["ich", "mich", "mir"],
    ["du", "dich", "dir"],
    ["er", "ihn", "ihm"],
    ["sie", "sie", "ihr"],
    ["es", "es", "ihm"],
    ["wir", "uns", "uns"],
    ["ihr", "euch", "euch"],
    ["sie", "sie", "ihnen"],
    ["Sie", "Sie", "Ihnen"],
  ],
};

const TENSE_GUIDE = {
  praesens: {
    title: "Präsens",
    description: "Le présent. Il sert aussi souvent pour le futur proche : Ich komme morgen."
  },
  perfekt: {
    title: "Perfekt",
    description: "Le passé le plus courant à l'oral. La plupart des verbes utilisent haben, mais les verbes de déplacement/changement d'état utilisent souvent sein."
  },
  praeteritum: {
    title: "Präteritum",
    description: "Passé surtout utilisé à l'écrit et dans les récits. Très important pour sein, haben et les verbes modaux."
  }
};

const IRREGULAR_VERBS = [
  { inf: "sein", fr: "être", praesens: ["bin","bist","ist","sind","seid","sind"], perfekt: "ist gewesen", praeteritum: "war", note: "Le verbe le plus important. Präteritum « war » très courant à l'oral." },
  { inf: "haben", fr: "avoir", praesens: ["habe","hast","hat","haben","habt","haben"], perfekt: "hat gehabt", praeteritum: "hatte", note: "Präteritum « hatte » très courant à l'oral." },
  { inf: "werden", fr: "devenir", praesens: ["werde","wirst","wird","werden","werdet","werden"], perfekt: "ist geworden", praeteritum: "wurde" },
  { inf: "können", fr: "pouvoir", praesens: ["kann","kannst","kann","können","könnt","können"], perfekt: "hat gekonnt", praeteritum: "konnte", note: "Modal : ich/er identiques, sans terminaison." },
  { inf: "müssen", fr: "devoir", praesens: ["muss","musst","muss","müssen","müsst","müssen"], perfekt: "hat gemusst", praeteritum: "musste" },
  { inf: "wollen", fr: "vouloir", praesens: ["will","willst","will","wollen","wollt","wollen"], perfekt: "hat gewollt", praeteritum: "wollte" },
  { inf: "sollen", fr: "devoir / être censé", praesens: ["soll","sollst","soll","sollen","sollt","sollen"], perfekt: "hat gesollt", praeteritum: "sollte" },
  { inf: "dürfen", fr: "avoir le droit", praesens: ["darf","darfst","darf","dürfen","dürft","dürfen"], perfekt: "hat gedurft", praeteritum: "durfte" },
  { inf: "mögen", fr: "aimer bien", praesens: ["mag","magst","mag","mögen","mögt","mögen"], perfekt: "hat gemocht", praeteritum: "mochte" },
  { inf: "wissen", fr: "savoir", praesens: ["weiß","weißt","weiß","wissen","wisst","wissen"], perfekt: "hat gewusst", praeteritum: "wusste" },
  { inf: "gehen", fr: "aller", praesens: null, perfekt: "ist gegangen", praeteritum: "ging" },
  { inf: "kommen", fr: "venir", praesens: null, perfekt: "ist gekommen", praeteritum: "kam" },
  { inf: "sehen", fr: "voir", praesens: ["sehe","siehst","sieht","sehen","seht","sehen"], perfekt: "hat gesehen", praeteritum: "sah" },
  { inf: "essen", fr: "manger", praesens: ["esse","isst","isst","essen","esst","essen"], perfekt: "hat gegessen", praeteritum: "aß" },
  { inf: "trinken", fr: "boire", praesens: null, perfekt: "hat getrunken", praeteritum: "trank" },
  { inf: "geben", fr: "donner", praesens: ["gebe","gibst","gibt","geben","gebt","geben"], perfekt: "hat gegeben", praeteritum: "gab" },
  { inf: "nehmen", fr: "prendre", praesens: ["nehme","nimmst","nimmt","nehmen","nehmt","nehmen"], perfekt: "hat genommen", praeteritum: "nahm" },
  { inf: "sprechen", fr: "parler", praesens: ["spreche","sprichst","spricht","sprechen","sprecht","sprechen"], perfekt: "hat gesprochen", praeteritum: "sprach" },
  { inf: "lesen", fr: "lire", praesens: ["lese","liest","liest","lesen","lest","lesen"], perfekt: "hat gelesen", praeteritum: "las" },
  { inf: "fahren", fr: "conduire / aller en véhicule", praesens: ["fahre","fährst","fährt","fahren","fahrt","fahren"], perfekt: "ist gefahren", praeteritum: "fuhr" },
  { inf: "laufen", fr: "courir / marcher", praesens: ["laufe","läufst","läuft","laufen","lauft","laufen"], perfekt: "ist gelaufen", praeteritum: "lief" },
  { inf: "schlafen", fr: "dormir", praesens: ["schlafe","schläfst","schläft","schlafen","schlaft","schlafen"], perfekt: "hat geschlafen", praeteritum: "schlief" },
  { inf: "helfen", fr: "aider (+ datif)", praesens: ["helfe","hilfst","hilft","helfen","helft","helfen"], perfekt: "hat geholfen", praeteritum: "half", note: "Toujours suivi du datif : Kannst du mir helfen ?" },
  { inf: "finden", fr: "trouver", praesens: null, perfekt: "hat gefunden", praeteritum: "fand", note: "Präsens régulier : du findest, er findet." },
  { inf: "bleiben", fr: "rester", praesens: null, perfekt: "ist geblieben", praeteritum: "blieb" },
  { inf: "stehen", fr: "être debout", praesens: null, perfekt: "hat gestanden", praeteritum: "stand" },
  { inf: "verstehen", fr: "comprendre", praesens: null, perfekt: "hat verstanden", praeteritum: "verstand", note: "ver + stehen : se conjugue comme stehen, sans ge- au Perfekt." },
  { inf: "tun", fr: "faire", praesens: ["tue","tust","tut","tun","tut","tun"], perfekt: "hat getan", praeteritum: "tat" },
  { inf: "heißen", fr: "s'appeler", praesens: ["heiße","heißt","heißt","heißen","heißt","heißen"], perfekt: "hat geheißen", praeteritum: "hieß" },
  { inf: "schreiben", fr: "écrire", praesens: null, perfekt: "hat geschrieben", praeteritum: "schrieb" }
];


const gp = (id, title, explanation, examples, pitfall = "", extra = {}) => ({
  id,
  title,
  explanation,
  examples: examples.map(([de, fr]) => ({ de, fr })),
  ...(pitfall ? { pitfall } : {}),
  ...extra,
});
const tbl = (headers, rows) => ({ headers, rows });
const CASE_LINK = { caseLink: true };

const GRAMMAR_LEVELS_CONTENT = [
  {
    level: "A1",
    points: [
      gp("word-order-main", "Ordre des mots : verbe en 2e position", "Dans une phrase d?clarative simple, le verbe conjugu? est toujours en deuxi?me position. Le premier ?l?ment peut ?tre le sujet, un compl?ment de temps ou un lieu ; si tu mets un compl?ment en premier, le sujet passe apr?s le verbe.", [["Ich lerne Deutsch.", "J'apprends l'allemand."], ["Heute lerne ich Deutsch.", "Aujourd'hui, j'apprends l'allemand."], ["In Berlin wohnt meine Schwester.", "Ma soeur habite ? Berlin."]], "Ne garde pas automatiquement l'ordre fran?ais sujet + verbe. Apr?s Heute, on dit Heute lerne ich, pas Heute ich lerne."),
      gp("yes-no-questions", "Questions oui/non : verbe en 1re position", "Pour une question ? laquelle on r?pond par oui ou non, le verbe conjugu? passe en premi?re position. On n'ajoute pas est-ce que : la position du verbe suffit.", [["Kommst du aus Frankreich?", "Viens-tu de France ?"], ["Hast du Zeit?", "As-tu le temps ?"], ["M?chten Sie Kaffee?", "Voulez-vous du caf? ?"]], "Ne traduis pas est-ce que par un mot allemand. C'est la structure verbale qui marque la question."),
      gp("w-fragen", "Les W-Fragen", "Les questions ouvertes commencent souvent par un mot en w. Le mot interrogatif vient en premier, puis le verbe conjugu?, puis le sujet.", [["Wo wohnst du?", "O? habites-tu ?"], ["Wann kommst du?", "Quand viens-tu ?"], ["Wohin gehst du?", "O? vas-tu ?"]], "wenn ne sert pas ? demander quand. Pour une question, utilise wann.", { table: tbl(["Mot", "Sens"], [["wer", "qui"], ["was", "quoi"], ["wo", "o?, position"], ["wann", "quand"], ["wie", "comment"], ["warum", "pourquoi"], ["woher", "d'o?"], ["wohin", "vers o?"]]) }),
      gp("present-tense", "Le pr?sent des verbes r?guliers", "Le pr?sent sert pour maintenant, les habitudes et souvent le futur proche quand un marqueur de temps est clair. Les verbes r?guliers prennent les terminaisons -e, -st, -t, -en, -t, -en.", [["Ich mache eine Pause.", "Je fais une pause."], ["Wir lernen jeden Abend.", "Nous ?tudions chaque soir."], ["Morgen besuche ich meine Freundin.", "Demain, je rends visite ? mon amie."]], "Le pr?sent allemand peut parler du futur si le contexte est clair : Morgen komme ich.", { table: tbl(["Sujet", "machen"], [["ich", "mache"], ["du", "machst"], ["er/sie/es", "macht"], ["wir", "machen"], ["ihr", "macht"], ["sie/Sie", "machen"]]) }),
      gp("sein-haben-present", "sein et haben au pr?sent", "sein et haben sont irr?guliers et indispensables. Apprends-les comme des blocs : ils servent seuls, mais aussi dans beaucoup de temps compos?s plus tard.", [["Ich bin m?de.", "Je suis fatigu?."], ["Sie hat ein Auto.", "Elle a une voiture."], ["Wir sind zu Hause.", "Nous sommes ? la maison."]], "Ne cherche pas une logique r?guli?re : ich bin et du bist doivent ?tre m?moris?s tels quels.", { table: tbl(["Sujet", "sein", "haben"], [["ich", "bin", "habe"], ["du", "bist", "hast"], ["er/sie/es", "ist", "hat"], ["wir", "sind", "haben"], ["ihr", "seid", "habt"], ["sie/Sie", "sind", "haben"]]) }),
      gp("personal-pronouns-nominative", "Pronoms personnels au nominatif", "Le nominatif sert surtout pour le sujet. Ces pronoms r?pondent ? la question qui fait l'action ? Les autres cas changent les formes ; ici on reste au sujet.", [["Ich wohne in Lyon.", "J'habite ? Lyon."], ["Sie kommt aus Wien.", "Elle vient de Vienne."], ["Sie sprechen Deutsch.", "Vous parlez allemand."]], "sie peut vouloir dire elle, ils ou elles. La majuscule Sie marque le vous de politesse.", { ...CASE_LINK, table: tbl(["Allemand", "Fran?ais"], [["ich", "je"], ["du", "tu"], ["er", "il"], ["sie", "elle"], ["es", "il/elle neutre"], ["wir", "nous"], ["ihr", "vous familier pluriel"], ["sie", "ils/elles"], ["Sie", "vous de politesse"]]) }),
      gp("indefinite-articles-kein", "ein/eine et la n?gation kein", "ein/eine correspond souvent ? un/une. Pour dire pas de devant un nom, l'allemand utilise kein, qui se comporte comme un article et prend des terminaisons.", [["Das ist ein Stuhl.", "C'est une chaise."], ["Ich habe keine Tasche.", "Je n'ai pas de sac."], ["Er hat kein Auto.", "Il n'a pas de voiture."]], "kein ne nie pas un verbe : pour je ne viens pas, dis Ich komme nicht, pas Ich komme kein.", { ...CASE_LINK, table: tbl(["Forme", "Exemple"], [["ein", "ein Tisch"], ["eine", "eine Lampe"], ["kein", "kein Tisch"], ["keine", "keine Lampe"]]) }),
      gp("nicht-kein", "N?gation : nicht vs kein", "kein nie un nom avec article ind?fini ou sans article. nicht nie un verbe, un adjectif, une information pr?cise ou toute une phrase.", [["Ich habe kein Auto.", "Je n'ai pas de voiture."], ["Ich komme heute nicht.", "Je ne viens pas aujourd'hui."], ["Das ist nicht teuer.", "Ce n'est pas cher."]], "Le fran?ais utilise ne... pas partout ; l'allemand choisit entre kein et nicht selon ce qui est ni?.", { ...CASE_LINK, table: tbl(["Utilise", "Pour nier"], [["kein", "un nom : pas de, aucun"], ["nicht", "un verbe, un adjectif, une information pr?cise"]]) }),
      gp("noun-plurals-patterns", "Pluriels des noms : grands mod?les", "Il n'y a pas une seule r?gle fiable pour le pluriel. ? A1, rep?re les grands mod?les et apprends le pluriel avec le nom : -e, -en, -er, umlaut + -e, -s.", [["Ich habe zwei B?cher.", "J'ai deux livres."], ["Hier sind viele Frauen.", "Il y a beaucoup de femmes ici."], ["Die Autos sind teuer.", "Les voitures sont ch?res."]], "Ne d?duis pas toujours le pluriel depuis le fran?ais. Note le pluriel d?s que tu apprends un nom.", { table: tbl(["Mod?le", "Exemple"], [["-e", "der Tisch, die Tische"], ["-en", "die Frau, die Frauen"], ["-er", "das Kind, die Kinder"], ["? + -e", "der Stuhl, die St?hle"], ["-s", "das Auto, die Autos"]]) }),
      gp("modal-verbs-present", "Verbes modaux au pr?sent", "Les modaux expriment une possibilit?, une obligation, une permission ou un souhait. Le modal est conjugu? en deuxi?me position ; l'autre verbe reste ? l'infinitif en fin de phrase.", [["Ich kann Deutsch sprechen.", "Je peux parler allemand."], ["Du musst heute arbeiten.", "Tu dois travailler aujourd'hui."], ["Darf ich hier sitzen?", "Ai-je le droit de m'asseoir ici ?"]], "Ne conjugue pas le verbe final : ich kann kommen, pas ich kann komme.", { table: tbl(["Modal", "Id?e"], [["k?nnen", "pouvoir, savoir faire"], ["m?ssen", "devoir, ?tre oblig?"], ["wollen", "vouloir"], ["sollen", "devoir selon une consigne"], ["d?rfen", "avoir le droit"]]) }),
      gp("moechten-polite", "m?chten pour exprimer un souhait poli", "m?chten signifie je voudrais, tu voudrais... Il est plus poli que wollen dans un caf?, un magasin ou une demande. wollen reste plus direct et peut sonner brusque.", [["Ich m?chte einen Kaffee.", "Je voudrais un caf?."], ["Wir m?chten bezahlen.", "Nous voudrions payer."], ["M?chten Sie Wasser?", "Voulez-vous de l'eau ?"]], "Je veux se traduit souvent par ich m?chte en contexte poli, pas par ich will.", { table: tbl(["Sujet", "m?chten"], [["ich", "m?chte"], ["du", "m?chtest"], ["er/sie/es", "m?chte"], ["wir", "m?chten"], ["ihr", "m?chtet"], ["sie/Sie", "m?chten"]]) }),
      gp("separable-verbs-present", "Verbes ? particule s?parable au pr?sent", "Certains verbes ont une particule qui se d?tache dans la phrase principale. Le verbe conjugu? reste en deuxi?me position et la particule va ? la fin.", [["Ich stehe um sieben Uhr auf.", "Je me l?ve ? sept heures."], ["Wir kaufen heute ein.", "Nous faisons les courses aujourd'hui."], ["Rufst du mich an?", "Tu m'appelles ?"]], "N'oublie pas la particule finale : ich stehe auf, pas seulement ich stehe."),
      gp("imperative", "L'imp?ratif", "L'imp?ratif sert ? donner une consigne, une invitation ou une instruction. Les formes principales sont du, ihr et Sie ; avec Sie, le pronom reste visible.", [["Komm bitte!", "Viens s'il te pla?t !"], ["Wartet hier!", "Attendez ici !"], ["?ffnen Sie das Fenster!", "Ouvrez la fen?tre !"]], "Avec Sie, garde Sie apr?s le verbe : Kommen Sie, ?ffnen Sie.", { table: tbl(["Forme", "Exemple"], [["du", "Komm!"], ["ihr", "Kommt!"], ["Sie", "Kommen Sie!"]]) }),
      gp("possessives", "Les possessifs", "Les possessifs indiquent ? qui appartient quelque chose : mein, dein, sein, ihr, unser, euer, Ihr. Ils se placent devant le nom et changent selon le genre, le nombre et le cas.", [["Das ist mein Bruder.", "C'est mon fr?re."], ["Wo ist deine Tasche?", "O? est ton sac ?"], ["Unsere Wohnung ist klein.", "Notre appartement est petit."]], "sein et ihr d?pendent du possesseur : sein Vater = son p?re ? lui ; ihr Vater = son p?re ? elle ou leur p?re.", { ...CASE_LINK, table: tbl(["Possessif", "Sens"], [["mein", "mon, ma, mes"], ["dein", "ton, ta, tes"], ["sein", "son, sa, ses ? lui"], ["ihr", "son, sa, ses ? elle / leur(s)"], ["unser", "notre, nos"], ["euer", "votre, vos"], ["Ihr", "votre, vos, politesse"]]) }),
      gp("es-gibt", "es gibt + accusatif", "es gibt signifie il y a. Le groupe nominal qui suit est ? l'accusatif, m?me si en fran?ais on ne voit pas de changement.", [["Es gibt einen Supermarkt.", "Il y a un supermarch?."], ["Es gibt hier keine Bank.", "Il n'y a pas de banque ici."], ["Gibt es ein Problem?", "Y a-t-il un probl?me ?"]], "Apr?s es gibt, le masculin devient einen : Es gibt einen Park.", CASE_LINK),
      gp("time-prepositions-am-um-im", "Pr?positions de temps : am, um, im", "am sert souvent pour les jours et moments de journ?e, um pour l'heure pr?cise, im pour les mois et saisons. Ces formes sont ? apprendre comme expressions de temps.", [["Der Kurs beginnt am Montag.", "Le cours commence lundi."], ["Wir treffen uns um acht Uhr.", "Nous nous retrouvons ? huit heures."], ["Im Januar ist es kalt.", "En janvier, il fait froid."]], "Ne traduis pas en/?/le m?caniquement : am Montag, um acht Uhr, im Januar.", { table: tbl(["Pr?position", "Usage", "Exemple"], [["am", "jour, date, moment", "am Montag"], ["um", "heure pr?cise", "um 8 Uhr"], ["im", "mois, saison", "im Januar"]]) }),
      gp("numbers-time-date", "Nombres, heure et date : r?gles cl?s", "? A1, il faut savoir comprendre les nombres, donner l'heure simple et dire une date. Pour l'heure officielle, on lit souvent heure + Uhr + minutes.", [["Es ist neun Uhr drei?ig.", "Il est neuf heures trente."], ["Heute ist der dritte April.", "Aujourd'hui, nous sommes le 3 avril."], ["Ich komme am Freitag.", "Je viens vendredi."]], "Les dates prennent souvent une terminaison : der dritte April, am dritten April."),
      gp("gern-lieber", "gern, lieber, am liebsten", "gern exprime ce qu'on aime faire. lieber compare deux pr?f?rences. am liebsten indique la pr?f?rence la plus forte.", [["Ich trinke gern Tee.", "J'aime boire du th?."], ["Ich trinke lieber Kaffee.", "Je pr?f?re boire du caf?."], ["Am liebsten trinke ich Wasser.", "Ce que je pr?f?re boire, c'est l'eau."]], "gern porte sur l'action, pas sur un objet seul : ich trinke gern Tee."),
      gp("ja-nein-doch", "ja, nein, doch", "ja confirme une phrase positive, nein refuse ou nie, doch contredit une question ou phrase n?gative. doch est essentiel car le fran?ais n'a pas un ?quivalent unique.", [["Kommst du? Ja, ich komme.", "Tu viens ? Oui, je viens."], ["Kommst du nicht? Doch, ich komme.", "Tu ne viens pas ? Si, je viens."], ["Hast du kein Auto? Nein, ich habe kein Auto.", "Tu n'as pas de voiture ? Non, je n'ai pas de voiture."]], "Pour r?pondre si ? une question n?gative, utilise doch, pas ja.", { table: tbl(["R?ponse", "Quand l'utiliser"], [["ja", "confirmer une question positive"], ["nein", "refuser ou confirmer une n?gation"], ["doch", "contredire une n?gation"]]) }),
      gp("coordinating-conjunctions", "aber, und, oder, denn : ordre normal", "Ces conjonctions relient deux ?l?ments ou deux phrases. Apr?s und, oder, aber et denn, l'ordre reste normal : le connecteur ne pousse pas le verbe ? la fin.", [["Ich lerne Deutsch, aber ich spreche noch langsam.", "J'apprends l'allemand, mais je parle encore lentement."], ["Ich bleibe zu Hause, denn ich bin krank.", "Je reste ? la maison car je suis malade."], ["Du kannst Tee trinken oder du nimmst Kaffee.", "Tu peux boire du th? ou tu prends du caf?."]], "denn ne fonctionne pas comme weil : apr?s denn, le verbe ne va pas ? la fin.", { table: tbl(["Conjonction", "Sens"], [["und", "et"], ["oder", "ou"], ["aber", "mais"], ["denn", "car"]]) })
    ]
  },

  {
    level: "A2",
    points: [
      gp("perfekt", "Le Perfekt", "Le Perfekt est le pass? le plus courant ? l'oral. Il se forme avec haben ou sein au pr?sent + participe pass? en fin de phrase. On ne l'utilise pas pour tout dans un style ?crit soutenu, mais il est central au niveau A2.", [["Ich habe Deutsch gelernt.", "J'ai appris l'allemand."], ["Wir sind nach Hamburg gefahren.", "Nous sommes all?s ? Hambourg."], ["Ich habe mein Zimmer aufger?umt.", "J'ai rang? ma chambre."]], "sein s'emploie surtout avec un changement de lieu ou d'?tat : gehen, fahren, kommen, aufstehen.", { table: tbl(["Type", "Forme fr?quente"], [["R?gulier", "ge- + radical + -t"], ["Irr?gulier", "souvent ge- + radical + -en"], ["Particule s?parable", "particule + ge + radical"], ["Verbe en -ieren", "pas de ge-"]]) }),
      gp("separable-vs-inseparable", "Particules s?parables et ins?parables", "Les particules s?parables se d?tachent dans la phrase principale et prennent ge- au Perfekt. Les pr?fixes ins?parables comme ver-, be-, er-, ent-, emp-, ge-, miss-, zer- ne se d?tachent jamais et ne prennent pas ge- au Perfekt.", [["Ich rufe dich sp?ter an.", "Je t'appelle plus tard."], ["Ich verstehe die Frage.", "Je comprends la question."], ["Sie hat die Rechnung bezahlt.", "Elle a pay? l'addition."]], "ver-, be- et er- ne se s?parent pas et ne prennent pas ge- au Perfekt : verstanden, bezahlt, erkl?rt.", { table: tbl(["Type", "Pr?sent", "Perfekt"], [["s?parable", "Ich stehe auf.", "Ich bin aufgestanden."], ["ins?parable", "Ich verstehe dich.", "Ich habe dich verstanden."], ["ins?parable", "Er bezahlt.", "Er hat bezahlt."]]) }),
      gp("praeteritum-core", "Pr?teritum de sein, haben et des modaux", "? A2, le Pr?teritum est surtout indispensable pour sein, haben et les verbes modaux. Ces formes sont tr?s fr?quentes ? l'?crit et aussi ? l'oral.", [["Ich war gestern krank.", "J'?tais malade hier."], ["Wir hatten keine Zeit.", "Nous n'avions pas le temps."], ["Sie musste arbeiten.", "Elle devait travailler."]], "Avec un modal au Pr?teritum, l'autre verbe reste infinitif ? la fin : ich musste arbeiten.", { table: tbl(["Infinitif", "ich/er", "wir/sie"], [["sein", "war", "waren"], ["haben", "hatte", "hatten"], ["k?nnen", "konnte", "konnten"], ["m?ssen", "musste", "mussten"], ["wollen", "wollte", "wollten"]]) }),
      gp("subordinate-clauses", "Subordonn?es avec weil, dass, wenn", "Avec weil, dass et wenn, le verbe conjugu? va ? la fin de la subordonn?e. Si la subordonn?e vient en premier, la principale commence ensuite par le verbe conjugu?.", [["Ich bleibe zu Hause, weil ich krank bin.", "Je reste ? la maison parce que je suis malade."], ["Wenn ich Zeit habe, koche ich.", "Si j'ai le temps, je cuisine."], ["Ich denke, dass Deutsch logisch ist.", "Je pense que l'allemand est logique."]], "wenn n'est pas le quand interrogatif : pour poser une question, utilise wann.", { table: tbl(["Mot", "Sens courant"], [["weil", "parce que"], ["dass", "que"], ["wenn", "si / quand habituel"]]) }),
      gp("indirect-questions", "Questions indirectes avec ob et W-Fragen", "Dans une question indirecte, le verbe conjugu? va ? la fin. ob introduit une question oui/non ; les mots en w restent utilis?s pour les questions ouvertes.", [["Ich wei? nicht, ob er Zeit hat.", "Je ne sais pas s'il a le temps."], ["Kannst du mir sagen, wann der Zug f?hrt?", "Peux-tu me dire quand le train part ?"], ["Sie fragt, warum ich lerne.", "Elle demande pourquoi j'?tudie."]], "Dans l'indirect, ne garde pas l'ordre de la question directe : ob er Zeit hat, pas ob hat er Zeit.", { table: tbl(["Direct", "Indirect"], [["Kommst du?", "Ich frage, ob du kommst."], ["Wann kommst du?", "Ich frage, wann du kommst."], ["Wo wohnst du?", "Ich wei? nicht, wo du wohnst."]]) }),
      gp("welcher-dieser", "welcher et dieser", "welcher signifie quel/lequel et sert ? choisir. dieser signifie ce/cet/cette/ces et d?signe quelque chose de pr?cis. Les deux se d?clinent comme des d?terminants.", [["Welchen Film sehen wir?", "Quel film regardons-nous ?"], ["Diese Tasche ist sch?n.", "Ce sac est beau."], ["Mit welchem Bus f?hrst du?", "Avec quel bus pars-tu ?"]], "welcher et dieser changent selon le cas : welcher Film, welchen Film, mit welchem Film.", CASE_LINK),
      gp("comparison", "Comparatif et superlatif", "Le comparatif sert ? comparer deux ?l?ments. Le superlatif exprime le plus haut degr?. Souvent : adjectif + -er, puis am + adjectif + -sten.", [["Berlin ist gr??er als Bonn.", "Berlin est plus grand que Bonn."], ["Dieses Zimmer ist kleiner.", "Cette chambre est plus petite."], ["Am besten lerne ich morgens.", "J'apprends le mieux le matin."]], "Pour dire plus ... que, l'allemand utilise als : gr??er als, schneller als.", { table: tbl(["Adjectif", "Comparatif", "Superlatif"], [["schnell", "schneller", "am schnellsten"], ["klein", "kleiner", "am kleinsten"], ["gut", "besser", "am besten"], ["viel", "mehr", "am meisten"]]) }),
      gp("reflexive-verbs", "Verbes r?fl?chis", "Un verbe r?fl?chi se construit avec un pronom qui renvoie au sujet : mich, dich, sich, uns, euch, sich. Certains sont r?fl?chis en allemand mais pas en fran?ais, ou inversement.", [["Ich freue mich.", "Je me r?jouis."], ["Wir treffen uns um acht.", "Nous nous retrouvons ? huit heures."], ["Sie interessiert sich f?r Musik.", "Elle s'int?resse ? la musique."]], "Ne calque pas toujours le fran?ais : se souvenir = sich erinnern an, mais attendre = warten auf.", { table: tbl(["Sujet", "Pronom"], [["ich", "mich"], ["du", "dich"], ["er/sie/es", "sich"], ["wir", "uns"], ["ihr", "euch"], ["sie/Sie", "sich"]]) }),
      gp("dative-verbs-common", "Verbes courants avec datif", "Certains verbes prennent un compl?ment au datif, m?me quand le fran?ais donne l'impression d'un COD. Apprends-les avec leur construction.", [["Kannst du mir helfen?", "Peux-tu m'aider ?"], ["Das Kleid gef?llt ihr.", "La robe lui pla?t."], ["Der Schl?ssel geh?rt dem Nachbarn.", "La cl? appartient au voisin."]], "helfen prend le datif : hilfst du mir, pas hilfst du mich.", { ...CASE_LINK, table: tbl(["Verbe", "Exemple"], [["helfen", "Ich helfe dir."], ["danken", "Ich danke Ihnen."], ["gefallen", "Das gef?llt mir."], ["geh?ren", "Das geh?rt meinem Bruder."]]) }),
      gp("um-zu", "um ... zu + infinitif vs weil", "um ... zu exprime un but quand le sujet est le m?me dans les deux parties. weil exprime une cause ou une explication, pas un objectif.", [["Ich lerne Deutsch, um in Deutschland zu arbeiten.", "J'apprends l'allemand pour travailler en Allemagne."], ["Sie geht in den Supermarkt, um Brot zu kaufen.", "Elle va au supermarch? pour acheter du pain."], ["Ich bleibe zu Hause, weil ich krank bin.", "Je reste ? la maison parce que je suis malade."]], "Si le sujet change, um ... zu ne convient pas. Utilise plut?t damit ? B1."),
      gp("polite-imperative", "Imp?ratif de politesse et tournures polies", "Avec Sie, l'imp?ratif garde le pronom apr?s le verbe. Pour ?tre plus diplomate, on utilise souvent k?nnten Sie ou w?rden Sie plut?t qu'un ordre direct.", [["Kommen Sie bitte herein.", "Entrez s'il vous pla?t."], ["K?nnten Sie mir bitte helfen?", "Pourriez-vous m'aider s'il vous pla?t ?"], ["W?rden Sie das bitte wiederholen?", "Voudriez-vous r?p?ter cela s'il vous pla?t ?"]], "?ffnen Sie est correct mais direct ; k?nnten Sie ?ffnen est souvent plus poli."),
      gp("fixed-prepositions", "Verbes avec pr?positions fixes", "Certains verbes appellent une pr?position pr?cise. Il faut apprendre le verbe avec sa pr?position comme une unit?, car la pr?position ne se d?duit pas toujours du fran?ais.", [["Ich warte auf den Bus.", "J'attends le bus."], ["Denkst du an mich?", "Penses-tu ? moi ?"], ["Ich freue mich ?ber dein Geschenk.", "Je suis content de ton cadeau."]], "La pr?position allemande ne copie pas toujours le fran?ais : warten auf, pas warten f?r.", { ...CASE_LINK, table: tbl(["Expression", "Sens"], [["warten auf", "attendre"], ["denken an", "penser ?"], ["sich freuen auf", "se r?jouir ? l'avance de"], ["sich freuen ?ber", "?tre content de quelque chose d?j? pr?sent/pass?"]]) }),
      gp("tekamolo-basic", "Date et ordre des compl?ments de temps", "Pour raconter une journ?e ou fixer un rendez-vous, l'allemand place souvent le compl?ment de temps t?t dans la phrase. La date ou le moment peut ouvrir la phrase, mais le verbe reste en deuxi?me position ; dans le Mittelfeld, retiens la tendance temps - mani?re - lieu.", [["Ich fahre morgen mit dem Zug nach Berlin.", "Je vais demain en train ? Berlin."], ["Wir lernen heute zusammen in der Bibliothek.", "Nous ?tudions aujourd'hui ensemble ? la biblioth?que."], ["Am Samstag gehe ich mit Freunden ins Kino.", "Samedi, je vais au cin?ma avec des amis."]], "Le verbe conjugu? reste en deuxi?me position, m?me si le temps est en premier : Am Samstag gehe ich."),
      gp("future-werden-present", "Futur avec werden vs pr?sent + morgen", "Le futur peut se former avec werden + infinitif, mais le pr?sent avec un marqueur de temps est tr?s courant pour parler d'un futur proche ou pr?vu.", [["Morgen gehe ich zum Arzt.", "Demain, je vais chez le m?decin."], ["Ich werde morgen lernen.", "J'?tudierai demain."], ["Wir besuchen n?chste Woche unsere Freunde.", "Nous rendons visite ? nos amis la semaine prochaine."]], "werden donne souvent un ton plus formel, une pr?diction ou une intention formul?e comme futur."),
      gp("als-wenn-past-first", "als vs wenn au pass? : premi?re approche", "Pour un ?v?nement unique dans le pass?, on utilise als. Pour une r?p?tition ou une condition, on utilise wenn. ? A2, retiens surtout als = quand une fois dans le pass?.", [["Als ich ein Kind war, wohnte ich in Paris.", "Quand j'?tais enfant, j'habitais ? Paris."], ["Wenn ich Ferien hatte, besuchte ich meine Oma.", "Quand j'avais des vacances, je rendais visite ? ma grand-m?re."], ["Wenn ich Zeit habe, komme ich.", "Si j'ai le temps, je viens."]], "als ne sert pas pour une condition actuelle. Pour si j'ai le temps, dis wenn ich Zeit habe."),
      gp("sequence-connectors", "zuerst, dann, danach, zum Schluss", "Ces connecteurs organisent un r?cit ou une proc?dure. Quand ils sont en premi?re position, le verbe conjugu? arrive juste apr?s.", [["Zuerst fr?hst?cke ich.", "D'abord, je prends le petit-d?jeuner."], ["Dann fahre ich zur Arbeit.", "Ensuite, je vais au travail."], ["Zum Schluss r?ume ich die K?che auf.", "Pour finir, je range la cuisine."]], "Apr?s dann ou danach en position 1, on inverse : Dann fahre ich, pas Dann ich fahre.")
    ]
  },

  {
    level: "B1",
    points: [
      gp("praeteritum-general", "Le Pr?teritum g?n?ral", "Au B1, on rencontre davantage le Pr?teritum des verbes courants, surtout dans les r?cits, articles et biographies. ? l'oral, le Perfekt reste fr?quent, sauf avec sein, haben et les modaux.", [["Er ging nach Hause.", "Il rentra / est rentr? ? la maison."], ["Sie kam sp?t an.", "Elle arriva tard."], ["Der Film begann um acht Uhr.", "Le film commen?a ? huit heures."]], "Ne remplace pas tout le Perfekt oral par le Pr?teritum : le registre change selon le verbe et le contexte."),
      gp("als-wenn-wann", "als, wenn, wann : r?capitulatif complet", "wann sert dans les questions directes ou indirectes. wenn sert pour si, pour quand r?p?t? ou futur. als sert pour un ?v?nement unique dans le pass?.", [["Wann kommst du?", "Quand viens-tu ?"], ["Wenn ich Zeit habe, rufe ich dich an.", "Si j'ai le temps, je t'appelle."], ["Als ich in Berlin war, besuchte ich ein Museum.", "Quand j'?tais ? Berlin, j'ai visit? un mus?e."]], "wenn n'est pas quand interrogatif. Dis Ich wei? nicht, wann er kommt, pas wenn er kommt.", { table: tbl(["Mot", "Usage"], [["wann", "question : quand ?"], ["wenn", "si / quand r?p?t? ou futur"], ["als", "quand unique dans le pass?"]]) }),
      gp("plusquamperfekt", "Plusquamperfekt : hatte/war + participe", "Le Plusquamperfekt exprime une action ant?rieure ? une autre action pass?e. Il se forme avec hatte ou war + participe pass?, selon le m?me choix que le Perfekt.", [["Ich hatte schon gegessen, als sie ankam.", "J'avais d?j? mang? quand elle est arriv?e."], ["Er war nach Hause gegangen, bevor ich kam.", "Il ?tait rentr? chez lui avant que j'arrive."], ["Wir hatten den Film gesehen.", "Nous avions vu le film."]], "Ne l'utilise pas pour tout pass? lointain : il sert surtout ? marquer avant une autre action pass?e."),
      gp("konjunktiv-ii", "Konjunktiv II poli et hypoth?tique", "Le Konjunktiv II sert ? ?tre poli, ? exprimer un souhait ou une hypoth?se. Les formes fr?quentes sont w?rde + infinitif, h?tte, w?re, k?nnte.", [["Ich h?tte gern einen Kaffee.", "Je voudrais un caf?."], ["K?nnten Sie mir helfen?", "Pourriez-vous m'aider ?"], ["Wenn ich Zeit h?tte, w?rde ich mehr lesen.", "Si j'avais le temps, je lirais davantage."]], "Avec sein, haben et les modaux, les formes w?re, h?tte, k?nnte sont souvent pr?f?r?es ? w?rde sein/haben/k?nnen."),
      gp("konjunktiv-ii-past", "Konjunktiv II pass?", "Pour parler d'une hypoth?se irr?elle dans le pass?, on utilise h?tte ou w?re + participe pass?. Cela correspond souvent ? j'aurais fait ou je serais all?.", [["Ich h?tte mehr lernen sollen.", "J'aurais d? ?tudier davantage."], ["Wenn ich Zeit gehabt h?tte, w?re ich gekommen.", "Si j'avais eu le temps, je serais venu."], ["Sie w?re gern geblieben.", "Elle serait volontiers rest?e."]], "Ne traduis pas j'aurais par w?rde haben : on dit ich h?tte gemacht."),
      gp("zu-infinitive", "zu + infinitif", "zu + infinitif compl?te de nombreux verbes, noms et expressions : versuchen zu, Lust haben zu, es ist wichtig zu. Avec les verbes s?parables, zu se place entre la particule et le verbe.", [["Ich versuche, jeden Tag Deutsch zu lernen.", "J'essaie d'apprendre l'allemand chaque jour."], ["Hast du Lust, ins Kino zu gehen?", "As-tu envie d'aller au cin?ma ?"], ["Es ist wichtig, fr?h aufzustehen.", "Il est important de se lever t?t."]], "Apr?s un modal, pas de zu : ich muss lernen, pas ich muss zu lernen."),
      gp("brauchen-zu", "brauchen nicht/nur zu", "brauchen + zu fonctionne surtout avec nicht ou nur et signifie ne pas avoir besoin de / il suffit de. Sans n?gation ou restriction, on pr?f?re souvent m?ssen ou sollen.", [["Du brauchst nicht zu kommen.", "Tu n'as pas besoin de venir."], ["Sie brauchen nur hier zu unterschreiben.", "Vous avez seulement besoin de signer ici."], ["Ich brauche das nicht zu erkl?ren.", "Je n'ai pas besoin d'expliquer cela."]], "Ne dis pas simplement ich brauche kommen. Dans cette construction, il faut zu."),
      gp("relative-clauses", "Les relatives", "Une relative donne une information sur un nom. Le pronom relatif ressemble ? der/die/das, mais son cas d?pend de son r?le dans la relative.", [["Das ist der Mann, der hier wohnt.", "C'est l'homme qui habite ici."], ["Das ist die Frau, die ich kenne.", "C'est la femme que je connais."], ["Das ist das Kind, dem ich helfe.", "C'est l'enfant que j'aide / ? qui j'aide."]], "Le pronom relatif d?pend de sa fonction dans la subordonn?e, pas seulement du nom en fran?ais.", CASE_LINK),
      gp("relative-preposition", "Relatives avec pr?position", "Quand une pr?position appartient ? la relative, elle se place avant le pronom relatif. Le cas du pronom d?pend de la pr?position.", [["Das ist der Mann, mit dem ich spreche.", "C'est l'homme avec qui je parle."], ["Die Stadt, in der ich wohne, ist gro?.", "La ville dans laquelle j'habite est grande."], ["Das Thema, ?ber das wir sprechen, ist wichtig.", "Le sujet dont nous parlons est important."]], "Ne laisse pas la pr?position ? la fin comme en fran?ais oral : mit dem, ?ber das.", CASE_LINK),
      gp("pronominal-adverbs", "Adverbes pronominaux : darauf, damit, worauf", "Avec une pr?position + chose/id?e, l'allemand utilise souvent da- ou wo- : damit, darauf, worauf, womit. Pour une personne, on garde pr?position + pronom.", [["Ich freue mich darauf.", "Je m'en r?jouis."], ["Womit besch?ftigst du dich?", "De quoi t'occupes-tu ?"], ["Dar?ber sprechen wir morgen.", "Nous en parlerons demain."]], "Pour une personne, ne dis pas damit : mit ihr, mit ihm, pas damit.", { table: tbl(["Question", "R?ponse"], [["Worauf wartest du?", "Ich warte darauf."], ["Womit schreibst du?", "Ich schreibe damit."], ["Mit wem sprichst du?", "Mit Anna."]]) }),
      gp("passive", "Le passif pr?sent et pass?", "Le passif met l'action au centre plut?t que la personne qui agit. Il se forme avec werden + participe pass?. Au pass? compos? : ist/sein + participe + worden.", [["Das Auto wird repariert.", "La voiture est r?par?e / en cours de r?paration."], ["Das Haus ist 1990 gebaut worden.", "La maison a ?t? construite en 1990."], ["Die E-Mail wurde gestern geschrieben.", "L'e-mail a ?t? ?crite hier."]], "Ne confonds pas werden futur et werden passif : le participe pass? signale le passif."),
      gp("passive-modal", "Passif avec verbes modaux", "Avec un modal, le passif garde werden ? l'infinitif en fin de groupe verbal. La structure exprime ce qui doit, peut ou devrait ?tre fait.", [["Das Formular muss ausgef?llt werden.", "Le formulaire doit ?tre rempli."], ["Die Rechnung kann online bezahlt werden.", "La facture peut ?tre pay?e en ligne."], ["Der Text sollte korrigiert werden.", "Le texte devrait ?tre corrig?."]], "Ne supprime pas werden : muss gemacht werden, pas muss gemacht."),
      gp("connectors-b1", "deshalb, trotzdem, obwohl", "Ces connecteurs expriment cons?quence ou opposition. deshalb et trotzdem occupent une position dans la phrase principale ; obwohl introduit une subordonn?e avec verbe ? la fin.", [["Ich bin krank, deshalb bleibe ich zu Hause.", "Je suis malade, donc je reste ? la maison."], ["Es regnet, trotzdem gehen wir spazieren.", "Il pleut, malgr? cela nous allons nous promener."], ["Obwohl ich m?de bin, lerne ich Deutsch.", "Bien que je sois fatigu?, j'apprends l'allemand."]], "obwohl fonctionne comme weil pour la place du verbe : verbe conjugu? ? la fin de la subordonn?e.", { table: tbl(["Connecteur", "Sens", "Position du verbe"], [["deshalb", "donc", "verbe juste apr?s"], ["trotzdem", "malgr? cela", "verbe juste apr?s"], ["obwohl", "bien que", "verbe ? la fin"]]) }),
      gp("genitive-prepositions-common", "Pr?positions courantes avec g?nitif", "wegen, trotz et w?hrend prennent souvent le g?nitif dans la langue standard ?crite. ? l'oral, on entend parfois le datif, mais pour un allemand soign?, apprends le g?nitif.", [["Wegen des Wetters bleiben wir zu Hause.", "? cause du temps, nous restons ? la maison."], ["Trotz des Regens gehen wir spazieren.", "Malgr? la pluie, nous allons nous promener."], ["W?hrend der Ferien arbeite ich nicht.", "Pendant les vacances, je ne travaille pas."]], "Ne calque pas toujours ? cause de + datif : wegen des Wetters est la forme standard.", CASE_LINK),
      gp("je-desto", "je ... desto", "je ... desto exprime une proportion : plus X, plus Y. La partie avec je est subordonn?e ; la partie avec desto d?clenche souvent l'inversion.", [["Je mehr ich ?be, desto besser spreche ich.", "Plus je pratique, mieux je parle."], ["Je fr?her wir anfangen, desto schneller sind wir fertig.", "Plus t?t nous commen?ons, plus vite nous avons fini."], ["Je l?nger ich lerne, desto sicherer werde ich.", "Plus j'?tudie longtemps, plus je deviens s?r de moi."]], "Ne mets pas desto seul au d?but d'une phrase normale : il r?pond ? je."),
      gp("adjectives-as-nouns", "Adjectifs substantiv?s", "Un adjectif peut devenir un nom : der Deutsche, die Kranke, etwas Neues. Il garde alors des terminaisons d'adjectif selon l'article, le genre, le nombre et le cas.", [["Der Deutsche spricht schnell.", "L'Allemand parle vite."], ["Ich habe etwas Neues gelernt.", "J'ai appris quelque chose de nouveau."], ["Viele Jugendliche nutzen soziale Medien.", "Beaucoup de jeunes utilisent les r?seaux sociaux."]], "Ne laisse pas l'adjectif sans terminaison : etwas Neues, pas etwas Neu.", CASE_LINK),
      gp("n-declension", "D?clinaison en -n des noms faibles", "Certains noms masculins prennent -n ou -en ? toutes les formes sauf le nominatif singulier. Beaucoup d?signent des personnes ou des ?tres vivants.", [["Ich sehe den Nachbarn.", "Je vois le voisin."], ["Ich helfe dem Studenten.", "J'aide l'?tudiant."], ["Die Nummer des Kunden fehlt.", "Le num?ro du client manque."]], "C'est un point li? aux cas : nominatif der Student, mais accusatif den Studenten.", { ...CASE_LINK, table: tbl(["Nominatif", "Autres formes fr?quentes"], [["der Nachbar", "den/dem/des Nachbarn"], ["der Student", "den/dem/des Studenten"], ["der Kunde", "den/dem/des Kunden"]]) }),
      gp("lassen-infinitive", "lassen + infinitif", "lassen + infinitif peut signifier laisser faire, faire faire, ou permettre qu'une action se produise. L'infinitif reste ? la fin.", [["Ich lasse mein Auto reparieren.", "Je fais r?parer ma voiture."], ["Lass mich schlafen!", "Laisse-moi dormir !"], ["Sie l?sst sich die Haare schneiden.", "Elle se fait couper les cheveux."]], "Ne traduis pas toujours par laisser : Ich lasse mein Auto reparieren = je fais r?parer ma voiture."),
      gp("seit-vor-time", "seit / vor + datif pour le temps", "seit indique une dur?e qui continue jusqu'? maintenant. vor indique un moment dans le pass?. Ces pr?positions prennent le datif.", [["Ich lerne seit zwei Jahren Deutsch.", "J'apprends l'allemand depuis deux ans."], ["Ich habe vor zwei Jahren angefangen.", "J'ai commenc? il y a deux ans."], ["Vor einer Woche war ich in Berlin.", "Il y a une semaine, j'?tais ? Berlin."]], "seit = depuis et continue encore ; vor = il y a.", CASE_LINK),
      gp("damit-um-zu", "damit vs um ... zu", "Les deux peuvent exprimer un but. um ... zu s'utilise si le sujet est le m?me. damit s'utilise notamment quand le sujet change.", [["Ich lerne Deutsch, um in Deutschland zu arbeiten.", "J'apprends l'allemand pour travailler en Allemagne."], ["Ich spreche langsam, damit du mich verstehst.", "Je parle lentement pour que tu me comprennes."], ["Ich ?ffne das Fenster, damit frische Luft hereinkommt.", "J'ouvre la fen?tre pour que l'air frais entre."]], "Avec damit, le verbe conjugu? va ? la fin : damit du mich verstehst."),
      gp("indirect-speech-simple", "Discours indirect simple", "Au B1, le discours indirect peut ?tre exprim? simplement avec dass, surtout ? l'oral. Le Konjunktiv I est plus avanc? et plus journalistique.", [["Er sagt, dass er krank ist.", "Il dit qu'il est malade."], ["Sie meint, dass der Termin wichtig ist.", "Elle pense que le rendez-vous est important."], ["Der Lehrer sagt, wir sollen ?ben.", "Le professeur dit que nous devons pratiquer."]], "Avec dass, le verbe va ? la fin : dass er krank ist, pas dass er ist krank.")
    ]
  },

  {
    level: "B2",
    points: [
      gp("konjunktiv-i-reported-speech", "Konjunktiv I et discours indirect de presse", "Le Konjunktiv I marque que l'information est rapport?e, surtout dans les articles et comptes rendus. Il ?vite de pr?senter les propos comme une certitude de l'auteur.", [["Der Minister sagte, die Lage sei ernst.", "Le ministre a d?clar? que la situation ?tait s?rieuse."], ["Die Zeitung berichtet, der T?ter habe gestanden.", "Le journal rapporte que l'auteur aurait avou?."], ["Sie erkl?rte, sie k?nne nicht teilnehmen.", "Elle a expliqu? qu'elle ne pouvait pas participer."]], "? l'oral quotidien, on utilise souvent dass + indicatif ; le Konjunktiv I est surtout presse, administratif ou soutenu.", { table: tbl(["Direct", "Indirect"], [["Er ist krank.", "Er sei krank."], ["Sie hat keine Zeit.", "Sie habe keine Zeit."], ["Wir kommen morgen.", "Sie k?men morgen."]]) }),
      gp("zustandspassiv", "Passif d'?tat vs passif d'action", "Le passif d'action avec werden d?crit un processus. Le passif d'?tat avec sein d?crit le r?sultat apr?s l'action. La diff?rence est importante pour ?viter l'ambigu?t?.", [["Das Gesch?ft ist geschlossen.", "Le magasin est ferm?."], ["Das Gesch?ft wird um acht geschlossen.", "Le magasin est ferm? ? huit heures."], ["Der Computer ist repariert.", "L'ordinateur est r?par?."]], "sein + participe n'est pas toujours un pass? compos? : ist ge?ffnet d?crit un ?tat.", { table: tbl(["Forme", "Sens"], [["Die T?r wird ge?ffnet.", "On ouvre la porte."], ["Die T?r ist ge?ffnet.", "La porte est ouverte."], ["Das Fenster wurde geschlossen.", "On a ferm? la fen?tre."], ["Das Fenster war geschlossen.", "La fen?tre ?tait ferm?e."]]) }),
      gp("participles-as-adjectives", "Participes I et II comme adjectifs", "Le participe I exprime une action en cours ou active. Le participe II exprime souvent un r?sultat ou une id?e passive. Comme adjectifs, ils prennent des terminaisons.", [["Das lachende Kind spielt im Garten.", "L'enfant qui rit joue dans le jardin."], ["Das geschriebene Buch liegt auf dem Tisch.", "Le livre ?crit est sur la table."], ["Die ge?ffneten Fenster bleiben offen.", "Les fen?tres ouvertes restent ouvertes."]], "Ne confonds pas lachend = qui rit et gelacht = ri. Le sens actif/passif change.", CASE_LINK),
      gp("participial-constructions", "Constructions participiales", "Les constructions participiales condensent une relative ou une proposition. Elles sont fr?quentes ? l'?crit, mais trop lourdes ? l'oral si on les accumule.", [["Die seit Jahren bestehende Regel wurde ge?ndert.", "La r?gle qui existait depuis des ann?es a ?t? modifi?e."], ["Die im Vertrag genannten Bedingungen gelten weiterhin.", "Les conditions mentionn?es dans le contrat restent valables."], ["Der gestern ver?ffentlichte Bericht sorgt f?r Diskussionen.", "Le rapport publi? hier suscite des discussions."]], "Si la phrase devient illisible, pr?f?re une relative avec der/die/das."),
      gp("nominalization", "Nominalisation : Verbalstil vers Nominalstil", "Le style nominal transforme une action en nom ou groupe nominal. Il est fr?quent dans les textes administratifs, universitaires et journalistiques, mais peut devenir lourd.", [["Beim Lesen lerne ich neue W?rter.", "En lisant, j'apprends de nouveaux mots."], ["Nach der Ankunft rief sie ihre Eltern an.", "Apr?s l'arriv?e, elle a appel? ses parents."], ["Wegen des Umbaus bleibt das B?ro geschlossen.", "En raison des travaux, le bureau reste ferm?."]], "Le style nominal est utile ? l'?crit, mais ? l'oral il peut sonner artificiel.", { ...CASE_LINK, table: tbl(["Verbalstil", "Nominalstil"], [["wenn man liest", "beim Lesen"], ["nachdem sie angekommen ist", "nach der Ankunft"], ["weil die Preise steigen", "wegen des Preisanstiegs"]]) }),
      gp("modal-past-irrealis", "Modaux au pass? irr?el", "Pour dire aurait pu, aurait d?, aurait voulu faire, l'allemand combine h?tte + infinitif lexical + modal ? l'infinitif. C'est une structure longue mais tr?s fr?quente ? B2.", [["Ich h?tte fr?her gehen k?nnen.", "J'aurais pu partir plus t?t."], ["Du h?ttest das sagen m?ssen.", "Tu aurais d? dire cela."], ["Wir h?tten l?nger bleiben wollen.", "Nous aurions voulu rester plus longtemps."]], "Le modal reste ? l'infinitif final : h?tte machen k?nnen, pas h?tte gekonnt machen."),
      gp("sich-lassen-infinitive", "sich lassen + infinitif", "sich lassen + infinitif exprime souvent la possibilit? passive : cela peut se faire, cela se lit facilement. C'est plus ?l?gant que man kann dans certains contextes.", [["Das l?sst sich machen.", "Cela peut se faire."], ["Der Text l?sst sich leicht verstehen.", "Le texte se comprend facilement."], ["Das Problem l?sst sich nicht schnell l?sen.", "Le probl?me ne peut pas se r?soudre rapidement."]], "Cette structure concerne souvent une chose, pas une personne qui se laisse faire."),
      gp("scheinen-drohen-pflegen-zu", "scheinen, drohen, pflegen + zu", "Ces verbes introduisent une nuance : scheinen = sembler, drohen = risquer de, pflegen = avoir l'habitude de dans un style soutenu. Ils se construisent avec zu + infinitif.", [["Er scheint krank zu sein.", "Il semble ?tre malade."], ["Die Lage droht sich zu verschlechtern.", "La situation risque de se d?t?riorer."], ["Sie pflegt fr?h aufzustehen.", "Elle a l'habitude de se lever t?t."]], "pflegen + zu est soutenu ; ? l'oral, on dira souvent gew?hnlich ou normalerweise."),
      gp("advanced-connectors-families", "Connecteurs avanc?s par familles", "? B2, les connecteurs servent ? structurer un raisonnement. Certains occupent une position dans la phrase principale et d?clenchent l'inversion ; d'autres introduisent une subordonn?e.", [["Die Kosten sind hoch, dennoch lohnt sich das Projekt.", "Les co?ts sont ?lev?s, pourtant le projet vaut la peine."], ["Die Nachfrage steigt; folglich m?ssen wir mehr produzieren.", "La demande augmente ; par cons?quent, nous devons produire davantage."], ["Er ist erfahren, allerdings fehlt ihm Zeit.", "Il est exp?riment?, toutefois il lui manque du temps."]], "Apr?s dennoch ou folglich en position 1, le verbe vient juste apr?s : dennoch lohnt es sich.", { table: tbl(["Famille", "Connecteurs"], [["opposition", "hingegen, allerdings, dennoch"], ["cons?quence", "folglich, somit, infolgedessen"], ["concession", "gleichwohl, obwohl, auch wenn"]]) }),
      gp("correlative-connectors", "Corr?latifs : sowohl... als auch, weder... noch", "Les corr?latifs relient deux ?l?ments de m?me niveau. Ils sont utiles pour ?crire plus pr?cis?ment, mais demandent une structure parall?le.", [["Sie spricht sowohl Deutsch als auch Englisch.", "Elle parle aussi bien allemand qu'anglais."], ["Ich habe weder Zeit noch Geld.", "Je n'ai ni temps ni argent."], ["Das ist zwar teuer, aber sehr n?tzlich.", "C'est certes cher, mais tr?s utile."]], "Garde des ?l?ments parall?les : weder heute noch morgen, pas une moiti? phrase et une moiti? nom.", { table: tbl(["Corr?latif", "Sens"], [["sowohl ... als auch", "aussi bien ... que"], ["weder ... noch", "ni ... ni"], ["entweder ... oder", "soit ... soit"], ["zwar ... aber", "certes ... mais"], ["nicht nur ... sondern auch", "non seulement ... mais aussi"]]) }),
      gp("extended-genitive-prepositions", "Pr?positions ?tendues avec g?nitif", "Les textes B2 utilisent souvent des pr?positions au g?nitif : anhand, aufgrund, bez?glich, infolge, mangels, angesichts. Elles condensent une relation logique en peu de mots.", [["Anhand der Daten kann man den Trend erkennen.", "? partir des donn?es, on peut reconna?tre la tendance."], ["Aufgrund des Streiks fallen viele Z?ge aus.", "En raison de la gr?ve, de nombreux trains sont annul?s."], ["Angesichts der Lage m?ssen wir handeln.", "Compte tenu de la situation, nous devons agir."]], "Ces formes sont surtout ?crites ou soutenues ; ? l'oral, des tournures plus simples sont souvent pr?f?r?es.", CASE_LINK),
      gp("sodass-so-dass", "sodass vs so ... dass", "sodass introduit une cons?quence : si bien que. so ... dass insiste sur l'intensit? : tellement ... que. Dans les deux cas, le verbe de la subordonn?e va ? la fin.", [["Es regnete stark, sodass wir zu Hause blieben.", "Il pleuvait fort, si bien que nous sommes rest?s ? la maison."], ["Es war so kalt, dass der See zufror.", "Il faisait si froid que le lac a gel?."], ["Sie sprach so leise, dass ich sie kaum verstand.", "Elle parlait si doucement que je la comprenais ? peine."]], "sodass = cons?quence globale ; so ... dass = degr? ou intensit?."),
      gp("funktionsverbgefuege", "Funktionsverbgef?ge courants", "Ces groupes verbe + nom sont fr?quents dans le style administratif et professionnel. Le verbe porte peu de sens ; le nom porte l'id?e principale.", [["Wir m?ssen eine Entscheidung treffen.", "Nous devons prendre une d?cision."], ["Die R?ume stehen zur Verf?gung.", "Les salles sont disponibles."], ["Diese L?sung kommt nicht in Frage.", "Cette solution n'entre pas en ligne de compte."]], "Ne traduis pas mot ? mot : zur Verf?gung stehen veut dire ?tre disponible.", { table: tbl(["Expression", "Sens simple"], [["eine Entscheidung treffen", "entscheiden"], ["zur Verf?gung stehen", "verf?gbar sein"], ["in Frage kommen", "m?glich sein"], ["eine Rolle spielen", "wichtig sein"]]) }),
      gp("mittelfeld-word-order", "Ordre des mots dans le Mittelfeld", "Entre le verbe conjugu? et la fin verbale, l'allemand organise les compl?ments. En tendance, les pronoms viennent avant les noms ; connu avant nouveau ; datif avant accusatif si les deux sont des noms.", [["Ich gebe dem Kind den Ball.", "Je donne le ballon ? l'enfant."], ["Ich gebe ihn dem Kind.", "Je le donne ? l'enfant."], ["Heute hat sie es mir erkl?rt.", "Aujourd'hui, elle me l'a expliqu?."]], "Il existe des variations selon l'information mise en valeur ; n'en fais pas une formule m?canique absolue.", { ...CASE_LINK, table: tbl(["Tendance", "Exemple"], [["pronom avant nom", "Ich gebe ihm das Buch."], ["accusatif pronom avant datif nom", "Ich gebe es dem Lehrer."], ["temps avant lieu", "Ich fahre morgen nach Berlin."]]) })
    ]
  },
  {
    level: "C1",
    points: [
      gp("subjective-modals", "Valeur subjective des verbes modaux", "? C1, les modaux peuvent exprimer une source ou une probabilit?, pas seulement une obligation. sollen rapporte une rumeur, d?rfte exprime une forte probabilit?, wollen rapporte une affirmation du sujet.", [["Die Firma soll verkauft werden.", "On dit que l'entreprise va ?tre vendue."], ["Das d?rfte kein Problem sein.", "Cela ne devrait probablement pas poser probl?me."], ["Sie will nichts davon gewusst haben.", "Elle pr?tend n'en avoir rien su."]], "Ne lis pas sollen uniquement comme devoir : Er soll reich sein ne veut pas dire il doit ?tre riche.", { table: tbl(["Forme", "Nuance"], [["Er soll reich sein.", "On dit qu'il est riche."], ["Er d?rfte zu Hause sein.", "Il est probablement chez lui."], ["Er will es gesehen haben.", "Il pr?tend l'avoir vu."]]) }),
      gp("future-ii-supposition", "Futur II pour la supposition", "Le Futur II peut exprimer une supposition sur un ?v?nement termin? : il aura probablement oubli?. Il se forme avec werden + participe + haben/sein.", [["Er wird es vergessen haben.", "Il l'aura probablement oubli?."], ["Sie wird schon angekommen sein.", "Elle sera s?rement d?j? arriv?e."], ["Du wirst davon geh?rt haben.", "Tu en as s?rement entendu parler."]], "Ce n'est pas seulement un futur chronologique ; c'est souvent une hypoth?se sur le pass?."),
      gp("bekommen-passive", "Passif avec bekommen", "Le passif avec bekommen met le b?n?ficiaire au centre. Il correspond souvent ? se voir offrir/donner/remettre quelque chose. On l'appelle aussi Rezipientenpassiv.", [["Er bekommt das Buch geschenkt.", "Il re?oit le livre en cadeau."], ["Sie bekam die Stelle angeboten.", "On lui a propos? le poste."], ["Ich bekomme den Termin best?tigt.", "On me confirme le rendez-vous."]], "Ce n'est pas le passif standard avec werden : ici, le destinataire devient sujet."),
      gp("modalpartikeln", "Modalpartikeln : doch, ja, eben, halt, mal, schon, wohl", "Les particules modales nuancent l'attitude du locuteur : rappel, ?vidence, impatience, douceur, r?signation, supposition. Elles sont tr?s fr?quentes ? l'oral et difficiles ? traduire.", [["Komm doch mit!", "Viens donc avec nous !"], ["Das ist ja interessant.", "Tiens, c'est int?ressant."], ["Kannst du mal helfen?", "Tu peux aider un instant ?"]], "Ne les traduis pas mot ? mot. Leur effet d?pend du ton, du contexte et de la relation entre les personnes.", { table: tbl(["Particule", "Nuance fr?quente"], [["doch", "rappel, contradiction douce"], ["ja", "?vidence partag?e"], ["eben/halt", "r?signation : c'est comme ?a"], ["mal", "adoucit une demande"], ["schon", "rassure ou conc?de"], ["wohl", "probabilit?"]]) }),
      gp("elevated-connectors-c1", "Connecteurs soutenus", "indes, zumal, sofern, es sei denn et geschweige denn structurent un raisonnement soutenu. Ils sont utiles dans les textes argumentatifs, mais peuvent para?tre trop formels ? l'oral quotidien.", [["Das Projekt ist teuer, indes notwendig.", "Le projet est co?teux, n?anmoins n?cessaire."], ["Wir fahren, sofern das Wetter gut bleibt.", "Nous partons ? condition que le temps reste bon."], ["Er kann kaum lesen, geschweige denn einen Vertrag verstehen.", "Il sait ? peine lire, sans m?me parler de comprendre un contrat."]], "Ces connecteurs sont puissants mais marqu?s ; dans une conversation simple, pr?f?re jedoch, weil ou wenn.", { table: tbl(["Connecteur", "Sens"], [["indes", "cependant, n?anmoins"], ["zumal", "d'autant plus que"], ["sofern", "? condition que"], ["es sei denn", "? moins que"], ["geschweige denn", "sans m?me parler de"]]) }),
      gp("ausklammerung-stylistic-order", "Ausklammerung et variations stylistiques", "L'Ausklammerung place un ?l?ment apr?s le cadre verbal pour all?ger ou mettre en valeur. C'est fr?quent avec des groupes longs, mais ? utiliser avec contr?le.", [["Er hat angerufen wegen des Termins morgen.", "Il a appel? au sujet du rendez-vous de demain."], ["Ich habe nicht gerechnet mit einer so schnellen Antwort.", "Je ne m'attendais pas ? une r?ponse aussi rapide."], ["Sie ist stolz auf das, was sie erreicht hat.", "Elle est fi?re de ce qu'elle a accompli."]], "N'utilise pas l'Ausklammerung pour ?viter l'ordre normal quand la phrase est simple."),
      gp("genitive-chains-nominal-style", "Cha?nes de g?nitifs et style nominal soutenu", "Le style soutenu accumule parfois des groupes nominaux et des g?nitifs. Cela permet une forte densit? d'information, mais peut devenir lourd si la phrase n'est pas bien structur?e.", [["Die Folgen der Entscheidung des Gerichts sind weitreichend.", "Les cons?quences de la d?cision du tribunal sont consid?rables."], ["Die Umsetzung der Ma?nahmen der Regierung beginnt sofort.", "La mise en oeuvre des mesures du gouvernement commence imm?diatement."], ["W?hrend der Pr?fung der Unterlagen wurden Fehler entdeckt.", "Pendant l'examen des documents, des erreurs ont ?t? d?couvertes."]], "Trop de g?nitifs rendent la phrase opaque ; une relative ou une phrase verbale peut ?tre plus claire.", CASE_LINK),
      gp("extended-infinitive-clauses", "Constructions infinitives ?tendues", "um ... zu exprime un but, ohne ... zu une absence d'action, anstatt ... zu une alternative non choisie. Ces structures partagent souvent le m?me sujet que la principale.", [["Sie spart Geld, um sp?ter zu studieren.", "Elle ?conomise de l'argent pour ?tudier plus tard."], ["Er ging, ohne sich zu verabschieden.", "Il est parti sans dire au revoir."], ["Anstatt zu warten, rief sie direkt an.", "Au lieu d'attendre, elle a appel? directement."]], "Si le sujet change, ces infinitives ne conviennent pas toujours ; utilise une subordonn?e compl?te."),
      gp("condition-without-wenn", "Condition sans wenn", "Dans un style plus soutenu ou concis, une condition peut commencer directement par le verbe conjugu? au Konjunktiv II. Le sens reste si..., mais wenn dispara?t.", [["H?tte ich Zeit, w?rde ich mitkommen.", "Si j'avais le temps, je viendrais avec vous."], ["W?re das Wetter besser, gingen wir spazieren.", "Si le temps ?tait meilleur, nous irions nous promener."], ["Sollten Sie Fragen haben, melden Sie sich bitte.", "Si vous avez des questions, contactez-nous."]], "Cette structure est plus formelle ; ? l'oral simple, wenn ich Zeit h?tte reste tr?s naturel."),
      gp("anticipatory-es", "Anticipation avec es", "es peut annoncer une subordonn?e ou un infinitif qui vient plus tard. Cela permet de placer une ?valuation au d?but : Es freut mich, dass...", [["Es freut mich, dass du gekommen bist.", "Je suis heureux que tu sois venu."], ["Es ist wichtig, regelm??ig zu ?ben.", "Il est important de pratiquer r?guli?rement."], ["Es ?berrascht mich, wie schnell du lernst.", "Cela me surprend ? quelle vitesse tu apprends."]], "Ne traduis pas toujours es par cela ; il sert souvent de support grammatical."),
      gp("registers-overview", "Registres : familier, standard, soutenu", "Au C1, il faut choisir le niveau de langue selon la situation. Une tournure famili?re peut ?tre parfaite avec des amis, mais d?plac?e dans un courrier professionnel ; une tournure soutenue peut sembler lourde ? l'oral.", [["Das kriegen wir schon hin.", "On va bien y arriver."], ["Das k?nnen wir schaffen.", "Nous pouvons y arriver."], ["Dies l?sst sich realisieren.", "Cela peut ?tre r?alis?."]], "Ne m?lange pas sans raison familier et soutenu dans le m?me texte : le registre doit rester coh?rent.", { table: tbl(["Registre", "Exemple"], [["familier", "Kriegen wir das hin?"], ["standard", "Schaffen wir das?"], ["soutenu", "L?sst sich das realisieren?"]]) })
    ]
  }
];
